### PR TITLE
Unit test for endROSCARetrieveFunds

### PR DESCRIPTION
**Pull request by rmerom**
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/32)

### CODE REVIEW

**Comment by shine2lay** [comment]
have you tested these test cases?

---

Review status: 0 of 3 files reviewed at latest revision, 19 unresolved discussions.

---

*[test/endOfROSCAUnitTest.js, line 11 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZT9_G_nzBWXxlbpQ_F:-KZT9_G_nzBWXxlbpQ_G:b-2myhc6) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L11)):*
> ```JavaScript
> contract('end of ROSCA unit test', function(accounts) {
>     const ROSCA_START_TIME_DELAY = 86400 + 10;
>     const TIME_TO_WAIT_FOR_ROSCA_TO_START = ROSCA_START_TIME_DELAY + 10;
> ```

ROSCA_START_TIME_DELAY would suffice already, don't really need to add extra 10 

---

*[test/endOfROSCAUnitTest.js, line 31 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTCxsjX3phBxxVg8fI:-KZTCxsjX3phBxxVg8fJ:b-c0ej79) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L31)):*
> ```JavaScript
>     // Runs the ROSCA, contributing funds as required, but never withdrawing - so that
>     // the contract ends in a surplus.
>     function* runFullRoscaNoWithdraw(rosca) {
> ```

(re iterating above) have you ran these test cases? to my knowledge , mocha frame work doesn't really like generator functions, that's why i added co.wrap around the functions.
Maybe I am wrong and it only doesn't like generator functions as a parameter for it() functions

---

*[test/endOfROSCAUnitTest.js, line 58 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTAiRo82qXPGoNWUeQ:-KZTAiRp9hT6xijNmyZ0:b-d0gtd7) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L58)):*
> ```JavaScript
>       
>       let forepersonCreditBefore = web3.eth.getBalance(accounts[0]);
>       let contractCredit = web3.eth.getBalance(accounts[0]);
> ```

i am about 80% sure that contract is not at accounts[0] address, it would most likely be in "rosca" variable 

---

*[test/endOfROSCAUnitTest.js, line 66 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTB-vhA4LlbXeVUFPM:-KZTB-vhA4LlbXeVUFPN:b7v3dl8) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L66)):*
> ```JavaScript
>       // Make sure the funds are retrieved back to the foreperson. There could be some extra because
>       // of selfdestruct refunds.
>       assert.isAtLeast(forepersonCreditAfter, forepersonCreditBefore + contractCredit);
> ```

this is going to be very tricky and unstable since you didn't account for the gas usage to call endROSCARetrieveFunds i.e what happens in the case that calling that function cost more gas than contract kill refunded gas ?

---

*[test/endOfROSCAUnitTest.js, line 85 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTDrumzP7vy5m9aTo-:-KZTDrumzP7vy5m9aTo0:b-10sr4g) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L85)):*
> ```JavaScript
>       yield* runFullRoscaNoWithdraw(rosca);
>       utils.increaseTime(ROUND_PERIOD_IN_DAYS * 86400);
>       yield rosca.startRound();
> ```

i think it would make more sense if this startRound call is before the increaseTime, in a normal scenario, you would clear the final round and then wait 1 more round time before killing the contract

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-:-KZT9xvlvTFNqvkkSrWA:b-yierxq)*

**Comment by rmerom** [comment]
i ran truffle test on all of them... let me know if you think i should do anything else?

---

Review status: 0 of 3 files reviewed at latest revision, 19 unresolved discussions.

---

*[test/endOfROSCAUnitTest.js, line 11 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZT9_G_nzBWXxlbpQ_F:-KZUZ6Xthb5mI1c_qTXt:b-88kilo) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L11)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

ROSCA_START_TIME_DELAY would suffice already, don't really need to add extra 10 
</blockquote></details>

Hmm I saw it in some of your unit tests, e..g https://github.com/WeTrustPlatform/rosca-contracts/blob/develop/test/addMemberUnitTest.js#L25 . Is it not needed?

---

*[test/endOfROSCAUnitTest.js, line 25 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZSBpghk87J7NWHR7TL-r1-25:-KZVB2PKBkZ66aI99xQL:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L25)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/endOfROSCAUnitTest.js, line 31 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTCxsjX3phBxxVg8fI:-KZUZQ5i-ZAkA89yglgt:b-6cnbsk) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L31)):*
Maybe that's true. It does run and tests pass, and if i change something in the tests they fail, so I'm not sure if and how we need to change that. Looking at the documentation, it  says:

> If you want to convert a co-generator-function into a regular function that returns a promise, you now use co.wrap(fn*).

I'm not sure how this relates to our case?

---

*[test/endOfROSCAUnitTest.js, line 58 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTAiRo82qXPGoNWUeQ:-KZUl-RCmpvgbCA0xYL3:b-af0gu3) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L58)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

i am about 80% sure that contract is not at accounts[0] address, it would most likely be in "rosca" variable 
</blockquote></details>

you're right, good catch! done.

---

*[test/endOfROSCAUnitTest.js, line 66 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTB-vhA4LlbXeVUFPM:-KZUl5TQh7E4s3rngH4I:b-tiqog8) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L66)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

this is going to be very tricky and unstable since you didn't account for the gas usage to call endROSCARetrieveFunds i.e what happens in the case that calling that function cost more gas than contract kill refunded gas ?
</blockquote></details>

right, and it did fail once i fixed as per your previous comment. I hope this new code makes more sense.

---

*[test/endOfROSCAUnitTest.js, line 85 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTDrumzP7vy5m9aTo-:-KZVAZ3D_zlQ9f19Irba:b-9yy7en) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L85)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

i think it would make more sense if this startRound call is before the increaseTime, in a normal scenario, you would clear the final round and then wait 1 more round time before killing the contract
</blockquote></details>

Right, done.

---

*[test/utils/utils.js, line 22 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZSBpghk87J7NWHR7TM-r1-22:-KZVBGAysivX1ZNI0tr1:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/utils/utils.js#L22)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Missing semicolon.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-:-KZUYdpALFWVp-kNgUhc:b74jemn)*

**Comment by shine2lay** [comment]
Review status: 0 of 3 files reviewed at latest revision, 18 unresolved discussions.

---

*[test/endOfROSCAUnitTest.js, line 11 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZT9_G_nzBWXxlbpQ_F:-KZXHLJ8cP2RaIVVfROp:bl3z3pc) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L11)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

Hmm I saw it in some of your unit tests, e..g https://github.com/WeTrustPlatform/rosca-contracts/blob/develop/test/addMemberUnitTest.js#L25 . Is it not needed?
</blockquote></details>

well you had +10 in ROSCA_START_TIME_DELAY already, that's why i said you probably wont need this

---

*[test/endOfROSCAUnitTest.js, line 31 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTCxsjX3phBxxVg8fI:-KZXGbSqSNPW7swsNLTW:bz9ip2j) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L31)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

Maybe that's true. It does run and tests pass, and if i change something in the tests they fail, so I'm not sure if and how we need to change that. Looking at the documentation, it  says:

> If you want to convert a co-generator-function into a regular function that returns a promise, you now use co.wrap(fn*).

I'm not sure how this relates to our case?
</blockquote></details>

ok, that means it only have problems with generator functions within it() functions. 

---

*[test/endOfROSCAUnitTest.js, line 58 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTAiRo82qXPGoNWUeQ:-KZXGsF6oPYO4TcEEXhO:b-u7ke4g) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L58)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

you're right, good catch! done.
</blockquote></details>

i don't see the new commit but i'll assume you already changed it locally

---

*[test/endOfROSCAUnitTest.js, line 66 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTB-vhA4LlbXeVUFPM:-KZXH4LhWZWJ3B69VIvd:b-zhbxsc) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L66)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

right, and it did fail once i fixed as per your previous comment. I hope this new code makes more sense.
</blockquote></details>

I don't see the new commit being pushed so i can't verify this 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32)*

**Review by shine2lay — APPROVED** [review]

**Comment by shine2lay** [comment]
please push the new commit 

---

Review status: 0 of 3 files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-:-KZXJ4LThmhLu-28cQW9:b-3s6eu3)*

**Comment by shine2lay** [comment]
Review status: 0 of 3 files reviewed at latest revision, 23 unresolved discussions.

---

*[test/endOfROSCAUnitTest.js, line 57 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZXSoxKdZF15LFFq1Yi:-KZXSoxLgxWjriZmqjfP:brj7b9r) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/9e7fd50207f8b159352879f0675f5033e1c6cd58/test/endOfROSCAUnitTest.js#L57)):*
> ```JavaScript
>       
>       let forepersonCreditBefore = web3.eth.getBalance(accounts[0]).toNumber();
>       let contractCredit = web3.eth.getBalance(rosca.address).toNumber();
> ```

be careful when using .toNumber() because it can cause trouble if balance is too big and it won't fit in the variable properly. 
I don't think it would cause a problem here but just something to keep in mind. 
here is where they explain a bit more :
https://github.com/ethereum/wiki/wiki/JavaScript-API#a-note-on-big-numbers-in-web3js

---

*[test/endOfROSCAUnitTest.js, line 62 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZXQGvlPEQSRAlwzWVJ:-KZXQGvmlz7bCtw8xRFh:bonki85) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/9e7fd50207f8b159352879f0675f5033e1c6cd58/test/endOfROSCAUnitTest.js#L62)):*
> ```JavaScript
>       yield rosca.endROSCARetrieveFunds({from: accounts[0]});
> 
>       let forepersonCreditAfter = web3.eth.getBalance(accounts[0]).toNumber();
> ```

I suggest naming this forepersonBalanceAfter because we use the var credit inside the ROSCA.
This could be a bit confusing with checking the credit variable from the ROSCA contract

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32)*

**Comment by rmerom** [comment]
Sorry, pushed now

---

Review status: 0 of 3 files reviewed at latest revision, 23 unresolved discussions.

---

*[test/endOfROSCAUnitTest.js, line 11 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZT9_G_nzBWXxlbpQ_F:-KZXUlJjWmfeOQc1Q0Z2:b-7xytzr) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L11)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

well you had +10 in ROSCA_START_TIME_DELAY already, that's why i said you probably wont need this
</blockquote></details>

I'm trying to understand - I think I based in on this code
https://github.com/WeTrustPlatform/rosca-contracts/blob/develop/test/cleanUpPreviousRoundUnitTest.js#L8
where MIN_START_DELAY is 10 more than darFromNow.
How are these cases different, or is the extra wait not needed in both?

---

*[test/endOfROSCAUnitTest.js, line 58 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTAiRo82qXPGoNWUeQ:-KZXVHzsxHevaCDxMqk0:b-koshsf) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L58)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

i don't see the new commit but i'll assume you already changed it locally
</blockquote></details>

right, i pushed now

---

*[test/endOfROSCAUnitTest.js, line 66 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZTB-vhA4LlbXeVUFPM:-KZXW57TKkn47JmkiVZJ:b8c9jmd) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a5271715695f8fb5d9008fa1977ac2620c504c76/test/endOfROSCAUnitTest.js#L66)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

I don't see the new commit being pushed so i can't verify this 
</blockquote></details>

pushed now, let me know if you still see an issue

---

*[test/endOfROSCAUnitTest.js, line 3 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZSBpghk87J7NWHR7TL-r2-3:-KZXV7R2nhLA5Jkgd1-w:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/9e7fd50207f8b159352879f0675f5033e1c6cd58/test/endOfROSCAUnitTest.js#L3)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Redefinition of 'Promise'.<br>'Promise' is defined but never used.
</blockquote></details>

Done.

---

*[test/endOfROSCAUnitTest.js, line 57 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZXSoxKdZF15LFFq1Yi:-KZXVUp-JgszXrwm-yR3:b-6tll2q) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/9e7fd50207f8b159352879f0675f5033e1c6cd58/test/endOfROSCAUnitTest.js#L57)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

be careful when using .toNumber() because it can cause trouble if balance is too big and it won't fit in the variable properly. 
I don't think it would cause a problem here but just something to keep in mind. 
here is where they explain a bit more :
https://github.com/ethereum/wiki/wiki/JavaScript-API#a-note-on-big-numbers-in-web3js
</blockquote></details>

Yes that's a fair point. The good news is that we ARE keeping everything in wei, thus in ints, so I think unless we're talking about more than 2^63 wei == 2^43 ether we should be good to go.

---

*[test/endOfROSCAUnitTest.js, line 62 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-KZXQGvlPEQSRAlwzWVJ:-KZXW31JrQF8R8RYBWs7:b-4k0685) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/9e7fd50207f8b159352879f0675f5033e1c6cd58/test/endOfROSCAUnitTest.js#L62)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

I suggest naming this forepersonBalanceAfter because we use the var credit inside the ROSCA.
This could be a bit confusing with checking the credit variable from the ROSCA contract
</blockquote></details>

Good point! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/32#-:-KZXUsBwEqXYx2zrNrpl:b-yc37b9)*

**Pull request merged**
