### PR TITLE
fix breaking Points , nothing has been upgraded yet

### PR DESCRIPTION
**Pull request by shine2lay**
the code should now work as before with truffle 3.0, non of the recommended standard upgrade has been added

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/133)

### CODE REVIEW

**Comment by rmerom** [comment]
Just to better understand: should this be working under truffle 3, but no longer under truffle 2?

**Comment by shine2lay** [comment]
i have not tried in truffle 2

**Comment by rmerom** [comment]
ok cool, let's just get everything under control in truffle 2 (the 2 remaining PRs), then proceed with this.
you might also want to update this branch with #134 to see it helps travis.
i'll meanwhile read about the upgrade and review this too.

**Comment by rmerom** [comment]
were you able to build on truffle 3 with this version?
(i'm asking because I can't see `DefaultBuilder` or one of the other builders in `truffle.js`)

**Comment by shine2lay** [comment]
that's only if you use ```truffle build``` , i don't think we use that command at all. I can add the Default builder if you would like me to

**Comment by shine2lay** [comment]
will PR later on a different branch

**Pull request closed without merging**
