### PR TITLE
add tests for fees for checking delinquency withdrawal rules

### PR DESCRIPTION
**Pull request by rmerom**
So that we have higher confidence in changes we make to ROSCA.sol, I added some tests about the expected fees, and the current withdrawal-for-delinquent requirement (which may be changed later).

Please note 3 tests are commented out. This is due to either known bugs in ROSCA.sol or features not yet implemented. 
@shine2lay as part of your PR, please also uncomment these tests.

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/59)

### CODE REVIEW

**Comment by rmerom** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/feesUnitTest.js, line 24 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/59#-K_LgN0VMAHBBbIuJbUf-r1-24:-K_LgssaiAp2QnQr-7z4:bq5glji) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/b9fe2557fff5ea696b7c39115bf09754531ad232/test/feesUnitTest.js#L24)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

'withdraw' is defined but never used.
</blockquote></details>

withdraw is used in the commented out sections

---

*[test/feesUnitTest.js, line 116 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/59#-K_LgN0VMAHBBbIuJbUf-r1-116:-K_LgvYaI1XLO9mQ2nqp:b-ygf0y8) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/b9fe2557fff5ea696b7c39115bf09754531ad232/test/feesUnitTest.js#L116)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

will not be too long when uncommented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/59)*

**Comment by shine2lay** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/feesUnitTest.js, line 138 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/59#-K_W1lMAmkpMQfD5UDRd:-K_W1lMAmkpMQfD5UDRe:b-scy2b3) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/b9fe2557fff5ea696b7c39115bf09754531ad232/test/feesUnitTest.js#L138)):*
> ```JavaScript
>   // }));
> 
>   // it('does not charge overcontributions that do not get used in the ROSCA and do get withdrawn', co(function* () {
> ```

duplicate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/59)*

**Review by shine2lay — APPROVED** [review]

**Comment by rmerom** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/feesUnitTest.js, line 138 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/59#-K_W1lMAmkpMQfD5UDRd:-K_WNPOKyEXrFdmt2ed1:b6ko9yj) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/b9fe2557fff5ea696b7c39115bf09754531ad232/test/feesUnitTest.js#L138)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

duplicate?
</blockquote></details>

the prev test was "... and does not get withdrawn", this one is "... and do get withdrawn"... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/59)*

**Comment by rmerom** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/feesUnitTest.js, line 139 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/59#-K_LgN0VMAHBBbIuJbUf-r2-139:-K_WOJh7_pZIHGj0yj_d:b-ygf0y8) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/08677e6c61e475eebbbdb17630bdb2e0d5c46c03/test/feesUnitTest.js#L139)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

will not be too long when uncommented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/59)*

**Pull request merged**
