### PR TITLE
Add new rosca types + tests

### PR DESCRIPTION
**Pull request by shine2lay**
For random Selection ROSCA, bidding is disabled. 

For Pre-Determined ROSCA, winner for each round is selected based on round number

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/162)

### CODE REVIEW

**Comment by blorange** [comment]
Looks good, please remember to eslint these ;)

---

Review status: 0 of 18 files reviewed at latest revision, 7 unresolved discussions.

---

*[contracts/ROSCA.sol, line 85 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiQpzYreIjeR5wflVx:-KkiQpzYreIjeR5wflVy:b-r61tu5) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/contracts/ROSCA.sol#L85)):*
> ```
>   // 2 : ROSCA where winners are selected through a ordered list (pre-determined ROSCA)
>   enum typesOfROSCA { biddingROSCA, randomSelectionROSCA, preDeterminedROSCA }
>   typesOfROSCA roscaType;
> ```

Since these are essentially integer constants, do you reckon we should UPPER_CASE them? That's usually what I would expect when dealing with constants.

---

*[contracts/ROSCA.sol, line 186 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiQRPrcWDVpDbwx8sF:-KkiQRPrcWDVpDbwx8sG:bkgkzwt) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/contracts/ROSCA.sol#L186)):*
> ```
>     * @dev Creates a new ROSCA and initializes the necessary variables. ROSCA starts after startTime.
>     * Creator of the contract becomes foreperson but not a participant (unless creator's address
>     *   is included in members_ parameter).
> ```

There do not appear to be any code changes regarding this, has this always been the case? If not, will it require some FE changes?

---

*[contracts/ROSCA.sol, line 417 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiRP5ongbcAsui1npD:-KkiRP5ongbcAsui1npE:b-eayie1) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/contracts/ROSCA.sol#L417)):*
> ```
>    * + New bid is lower than the lowest bid so far.
>    */
>   function bid(uint256 bid) onlyFromMember onlyIfRoscaNotEnded onlyIfEscapeHatchInactive onlyBiddingROSCA external {
> ```

Just a thought, different sets of source code might be a good thing to think about here. Functions unique to each type of ROSCA will take up unnecessary and valuable blockchain space.

A 300-line contract of mine is now up to about $8 to deploy at the default gas price :(

---

*[test/4MemberFullRoscaTest.js, line 20 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiSCCeggWFZJtLY3RR:-KkiSCCeggWFZJtLY3RS:b7nwn1w) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/test/4MemberFullRoscaTest.js#L20)):*
> ```JavaScript
> let erc20Rosca;
> let rosca;
> ```

I have not reviewed this file this time around, am I correct in thinking it was also in another PR?

---

*[test/feesUnitTest.js, line 68 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiSelx6lXAwiXIEQIf:-KkiSelx6lXAwiXIEQIg:bbi2rhk) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/test/feesUnitTest.js#L68)):*
> ```JavaScript
>     let expectedWithrewAmount = utils.afterFee(BID_TO_PLACE)  +
>       utils.afterFee(INDIVIDUAL_DISCOUNT)
>     assert.equal(withdrewAmount, expectedWithrewAmount, "fees taken out doesn't match theoretical calculations");
> ```

s/expectedWithrewAmount/expectedWithdrewAmount

---

*[test/preDeterminedRoscaTest.js, line 27 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiToNJqZMrYJ6usy2I:-KkiToNKU9S9NHe98nJf:b6tkni6) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/test/preDeterminedRoscaTest.js#L27)):*
> ```JavaScript
> 
>     yield utils.assertThrows(rosca.bid(0, VALID_BID))
>     yield rosca.contribute(0, consts.CONTRIBUTION_SIZE) // p0 should be allowed to bid in bidding ROSCA after contribution
> ```

Is this comment relevant? AFAICT this isn't a bidding ROSCA and we're not expecting anyone to be able to bid.

---

*[test/randomSelectionROSCATest.js, line 27 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiTzN1S2JYXDZ5E7qd:-KkiTzN2ZnhfDuNsyysR:b-8a05gs) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/test/randomSelectionROSCATest.js#L27)):*
> ```JavaScript
> 
>     yield utils.assertThrows(rosca.bid(1, VALID_BID))
>     yield rosca.contribute(0, consts.CONTRIBUTION_SIZE) // p0 should be allowed to bid in bidding ROSCA after contribution
> ```

As above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-:-KkiUWydIJ6HmMFxfgh-:b2t5agk)*

**Comment by shine2lay** [comment]
i took care of eslint in refactor part 4, i'll make sure to eslint the newly added files

---

Review status: 0 of 18 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 85 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiQpzYreIjeR5wflVx:-KklQmf14pBNlop_6PSt:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/contracts/ROSCA.sol#L85)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

Since these are essentially integer constants, do you reckon we should UPPER_CASE them? That's usually what I would expect when dealing with constants.
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 186 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiQRPrcWDVpDbwx8sF:-KklOnIZLxiQt-MzmJZD:bgf936h) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/contracts/ROSCA.sol#L186)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

There do not appear to be any code changes regarding this, has this always been the case? If not, will it require some FE changes?
</blockquote></details>

I removed one line in the constructor , https://github.com/WeTrustPlatform/rosca-contracts/blob/develop/contracts/ROSCA.sol#L204 should no longer be a part of the code. FE will also have to make some changes i believe because constructor will be expecting different paramaters

---

*[contracts/ROSCA.sol, line 417 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiRP5ongbcAsui1npD:-KklPHG0zBng91RJKHqg:bebkz4z) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/contracts/ROSCA.sol#L417)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

Just a thought, different sets of source code might be a good thing to think about here. Functions unique to each type of ROSCA will take up unnecessary and valuable blockchain space.

A 300-line contract of mine is now up to about $8 to deploy at the default gas price :(
</blockquote></details>

I think the reason why didn't create three different contract is that it'll be a pain to maintain. 

---

*[test/4MemberFullRoscaTest.js, line 20 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiSCCeggWFZJtLY3RR:-KklMuWyFtPoCJQzQmM9:b-5g9o7c) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/test/4MemberFullRoscaTest.js#L20)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

I have not reviewed this file this time around, am I correct in thinking it was also in another PR?
</blockquote></details>

yes, done

---

*[test/feesUnitTest.js, line 68 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiSelx6lXAwiXIEQIf:-KklNF5m69AvFrpx6wqx:b-3j3vrc) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/test/feesUnitTest.js#L68)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

s/expectedWithrewAmount/expectedWithdrewAmount
</blockquote></details>

this will be changed in another PR, which will be in refactor part 4

---

*[test/preDeterminedRoscaTest.js, line 27 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiToNJqZMrYJ6usy2I:-KklNnHDl4RNLF3V0f0f:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/test/preDeterminedRoscaTest.js#L27)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

Is this comment relevant? AFAICT this isn't a bidding ROSCA and we're not expecting anyone to be able to bid.
</blockquote></details>

Done.

---

*[test/randomSelectionROSCATest.js, line 27 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiTzN1S2JYXDZ5E7qd:-KklNtzM4vu5pcTgiOOI:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/test/randomSelectionROSCATest.js#L27)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

As above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-:-KklNuyGOiVHiJaDO_tu:bf5p9cm)*

**Comment by blorange** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[contracts/ROSCA.sol, line 417 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiRP5ongbcAsui1npD:-KknBGWbOyG3-ZSXp815:b-9gn8kg) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/contracts/ROSCA.sol#L417)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

I think the reason why didn't create three different contract is that it'll be a pain to maintain. 
</blockquote></details>

I agree that it will be more to maintain, but I think we should be keeping the interests of our users at the forefront of our mind.

I think we should have a discussion about this with @rmerom.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162)*

**Comment by rmerom** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[contracts/ROSCA.sol, line 417 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162#-KkiRP5ongbcAsui1npD:-Kkq1HN6ABiItKRgI_M2:b5k6s08) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/abbd3e1db4659157d60d464bceae8edfa5edb1de/contracts/ROSCA.sol#L417)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

I agree that it will be more to maintain, but I think we should be keeping the interests of our users at the forefront of our mind.

I think we should have a discussion about this with @rmerom.
</blockquote></details>

I agree that maintaining 3 different types of contracts would be a pain to maintain. 
What we can probably do, not necessarily right now, is separate the business logic to its own library contract and have users deploy only a lean contract. 
That way deployment would cost less, but we will still have a more maintainable codebase

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/162)*

**Review by sihoang — APPROVED** [review]
I only reviewed the smart contract. Please make sure the tests pass

**Pull request merged**
