### PR TITLE
PR ready , First Test Case

### PR DESCRIPTION
**Pull request by shine2lay**
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/15)

### CODE REVIEW

**Comment by rmerom** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 5 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYuqVsQGm_g55YYwCMR:-KYuqVsQGm_g55YYwCMS:b-8qvfx8) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/README.md#L5)):*
> ```Markdown
> ``` npm install co ```
> 
> run testrpc in ``` cat testrpc_command.txt```
> ```

i think this should be something like:

run testrpc: 
```  `cat testrpc_command.txt` ```
```


---

*[README.md, line 5 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYuqs8JC26_C2yfLAQt:-KYuqs8JC26_C2yfLAQu:bqy47ln) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/README.md#L5)):*
> ```Markdown
> ``` npm install co ```
> 
> run testrpc in ``` cat testrpc_command.txt```
> ```

actually we can change all of this once the other PR is pushed to:
``` tools/build/run-tests.sh ```
```


---

*[migrations/2_deploy_contracts.js, line 6 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYur-uuFcocz7MHecmX:-KYur-uve9PKX42x2wBb:b-iuwvmg) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/migrations/2_deploy_contracts.js#L6)):*
> ```JavaScript
> 
>   var latestBlock = web3.eth.getBlock("latest");
>   simulatedTimeNow = latestBlock.timestamp;
> ```

can you add a quick explanation what this is? same in 3_deploy_test_contracts.js below

---

*[test/addMemberUnitTest.js, line 13 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYur88ibvXNAXQ_-xTN:-KYur88ibvXNAXQ_-xTO:b-ix7xgs) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/test/addMemberUnitTest.js#L13)):*
> ```JavaScript
>  (done) - add non Member , check members.call().alive is true (deals with #2 flow case)
> 
>  */
> ```

please remove comment

---

*[test/addMemberUnitTest.js, line 17 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYurQWDmwwHDcMG3zYY:-KYurQWDmwwHDcMG3zYZ:b-knajxj) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/test/addMemberUnitTest.js#L17)):*
> ```JavaScript
> contract('ROSCA addMember Unit test', function(accounts) {
> 
>     it("add Existing member, throw", function () {
> ```

nit: would be nice to change to a readable sentence as the errors become more readable then, e.g.
```it("throws when adding an existing member", function() {```

same in other tests
```


---

*[test/addMemberUnitTest.js, line 26 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYurf0UUbWFnscRSRmG:-KYurf0UUbWFnscRSRmH:biq3t1q) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/test/addMemberUnitTest.js#L26)):*
> ```JavaScript
>         });
>     });
>     it("check if membersAddresses.length goes up by 1 after calling", co(function *() {
> ```

plz add blank line between tests (same also below)

---

*[test/addMemberUnitTest.js, line 33 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYusGz-vU2Jru4GxSSZ:-KYusGz-vU2Jru4GxSS_:b-npce8u) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/test/addMemberUnitTest.js#L33)):*
> ```JavaScript
>         return assert.equal(member, accounts[4], "member's address didn't get registered properly");
>     }));
>     it("check if the address exists in members mapping", co(function *() {
> ```

nit: you might want to merge this test with the previous one. It's just adding more checks to the same scenario (adding a member) so we can do one test with multiple assertions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15)*
<!-- Sent from Reviewable.io -->

**Comment by shine2lay** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 5 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYuqVsQGm_g55YYwCMR:-KYuuLZkb0q2Wp9u3ZEY:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/README.md#L5)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

i think this should be something like:

run testrpc: 
```  `cat testrpc_command.txt` ```
</blockquote></details>

Done.

---

*[README.md, line 5 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYuqs8JC26_C2yfLAQt:-KYuucJFziE9I0i21vEh:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/README.md#L5)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

actually we can change all of this once the other PR is pushed to:
``` tools/build/run-tests.sh ```
</blockquote></details>

Done.

---

*[migrations/2_deploy_contracts.js, line 6 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYur-uuFcocz7MHecmX:-KYuv9JBGVXJBvCxvq84:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/migrations/2_deploy_contracts.js#L6)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

can you add a quick explanation what this is? same in 3_deploy_test_contracts.js below
</blockquote></details>

Done.

---

*[test/addMemberUnitTest.js, line 13 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYur88ibvXNAXQ_-xTN:-KYuuiQq3zx6wv2PjNzk:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/test/addMemberUnitTest.js#L13)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

please remove comment
</blockquote></details>

Done.

---

*[test/addMemberUnitTest.js, line 17 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYurQWDmwwHDcMG3zYY:-KYuwCg1ARFLjmmKeVB9:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/test/addMemberUnitTest.js#L17)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

nit: would be nice to change to a readable sentence as the errors become more readable then, e.g.
```it("throws when adding an existing member", function() {```

same in other tests


</blockquote></details>

Done.

---

*[test/addMemberUnitTest.js, line 26 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYurf0UUbWFnscRSRmG:-KYuwJ8rR37peQmXzjL5:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/test/addMemberUnitTest.js#L26)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

plz add blank line between tests (same also below)
</blockquote></details>

Done.

---

*[test/addMemberUnitTest.js, line 33 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYusGz-vU2Jru4GxSSZ:-KYuwK1DyeHrP-j9BCEw:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/918e595935f8e923cf681a565019c25105a69dac/test/addMemberUnitTest.js#L33)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

nit: you might want to merge this test with the previous one. It's just adding more checks to the same scenario (adding a member) so we can do one test with multiple assertions
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15)*

**Comment by rmerom** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 7 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYyYRQ0t6dEMXp_XGTc:-KYyYRQ1YMpC_JBZK0Of:b-k10qr6) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/27ab2727d0535e9c334bd4fe273cb354155a862b/README.md#L7)):*
> ```Markdown
> run testrpc:
> 
>  ``` cat testrpc_command.txt```
> ```

extra space?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15)*

**Review by rmerom — APPROVED** [review]
Please push after addressing the last small comment

**Comment by shine2lay** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 7 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15#-KYyYRQ0t6dEMXp_XGTc:-KYz5tuKQRpeOXTXDdzU:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/27ab2727d0535e9c334bd4fe273cb354155a862b/README.md#L7)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

extra space?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15)*

**Comment by rmerom** [comment]
Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/15)*

**Pull request merged**
