### PR TITLE
Bug fixes , look at google spreadsheet for details

### PR DESCRIPTION
**Pull request by shine2lay**
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/12)

### CODE REVIEW

**Comment by rmerom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[contracts/ROSCA.sol, line 67 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtn1bJFpDIr40j-um9:-KYtn1bJFpDIr40j-umA:b3kqx) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a1d12dda673f6e4f9dfa6ffe5bed0417f2d12fdf/contracts/ROSCA.sol#L67)):*
> ```
>   }
>   modifier notEnded {
>     if(endOfROSCA)
> ```

.

---

*[contracts/ROSCA.sol, line 137 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtqaPOjm1UdfQCbbHK:-KYtqaPOjm1UdfQCbbHL:b3kqx) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a1d12dda673f6e4f9dfa6ffe5bed0417f2d12fdf/contracts/ROSCA.sol#L137)):*
> ```
>       uint256 semi_random = block.number % membersAddresses.length;
>       for (uint16 i = 0; i < membersAddresses.length; i++) {
>         if(!members[membersAddresses[(semi_random + i) % membersAddresses.length]].paid &&
> ```

.

---

*[contracts/ROSCA.sol, line 141 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtqusoCCjD0T8GsK9k:-KYtquspCTJQVbI7xIvU:bd5d6lg) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/10173be18c67052659b0a37bf0735cdd44e0cfe1/contracts/ROSCA.sol#L141)):*
> ```
>       lowestBid--;
>     }
>     totalDiscounts += contributionSize * membersAddresses.length - lowestBid;
> ```

indentation

---

*[contracts/ROSCA.sol, line 147 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtqd508kw-YEw0rJl5:-KYtqd508kw-YEw0rJl6:b-y93u5v) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a1d12dda673f6e4f9dfa6ffe5bed0417f2d12fdf/contracts/ROSCA.sol#L147)):*
> ```
>       lowestBid--;
>     }
>     if(winnerAddress == 0) {
> ```

- space after if
- let's add a comment such as "no potential winner"

---

*[contracts/ROSCA.sol, line 154 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtrHRgO8Q5UGel9iOG:-KYtrHRgO8Q5UGel9iOH:b5uq0ei) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/10173be18c67052659b0a37bf0735cdd44e0cfe1/contracts/ROSCA.sol#L154)):*
> ```
>    */
>   function contribute() payable {
>     if (!members[msg.sender].alive || endOfROSCA) throw;
> ```

do we not need the endOfROSCA check anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12)*

**Comment by shine2lay** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[contracts/ROSCA.sol, line 67 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtn1bJFpDIr40j-um9:-KYtsAyqPP62WAYg78-H:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a1d12dda673f6e4f9dfa6ffe5bed0417f2d12fdf/contracts/ROSCA.sol#L67)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 137 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtqaPOjm1UdfQCbbHK:-KYtsB_4E0pM_ZNqQWR8:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a1d12dda673f6e4f9dfa6ffe5bed0417f2d12fdf/contracts/ROSCA.sol#L137)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 141 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtqusoCCjD0T8GsK9k:-KYtsNXlsmJKHCI-syhx:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/10173be18c67052659b0a37bf0735cdd44e0cfe1/contracts/ROSCA.sol#L141)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

indentation
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 147 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtqd508kw-YEw0rJl5:-KYtrp9AuRnh379LN3An:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a1d12dda673f6e4f9dfa6ffe5bed0417f2d12fdf/contracts/ROSCA.sol#L147)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

- space after if
- let's add a comment such as "no potential winner"
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 154 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtrHRgO8Q5UGel9iOG:-KYtrrPhsgy956HgUmgO:b-dlqddx) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/10173be18c67052659b0a37bf0735cdd44e0cfe1/contracts/ROSCA.sol#L154)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

do we not need the endOfROSCA check anymore?
</blockquote></details>

we are using NotEnded Modifier

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12)*

**Comment by rmerom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[contracts/ROSCA.sol, line 154 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtrHRgO8Q5UGel9iOG:-KYtug79ZQQR3RewiA8p:bafhag7) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/10173be18c67052659b0a37bf0735cdd44e0cfe1/contracts/ROSCA.sol#L154)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

we are using NotEnded Modifier
</blockquote></details>

Oh right!

---

*[contracts/ROSCA.sol, line 135 at r3](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12#-KYtuaFEaPygnVYL3WwD:-KYtuaFEaPygnVYL3WwE:b-u7pbso) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5014833a0dbd21ace47f0e0811ef0ef5decd0f6f/contracts/ROSCA.sol#L135)):*
> ```
>       uint256 semi_random = now % membersAddresses.length;
>       for (uint16 i = 0; i < membersAddresses.length; i++) {
>         address index = membersAddresses[(semi_random + i) % membersAddresses.length];
> ```

consider s/index/candidate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12)*

**Comment by rmerom** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/12)*

**Review by rmerom — APPROVED** [review]

**Pull request merged**
