### PR TITLE
[DO NOT MERGE] add support for two new types of rosca

### PR DESCRIPTION
**Pull request by shine2lay**
1. Lottery Rosca , where bidding is not allowed and winners are chosen semi randomly every period
2. PreOrdered Rosca, where winners are chosen in the same order they are passed in during creation

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/154)

### CODE REVIEW

**Comment by rmerom** [comment]
Looks good!

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 20 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEsq4BhlzpLT7KaHED:-KjEsq4BhlzpLT7KaHEE:b-361xpp) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L20)):*
> ```
> contract ROSCA {
> 
>   uint16 public constant CONTRACT_VERSION  = 2;
> ```

i think we'll want to increment the contract version, because the constructor signature has changed

---

*[contracts/ROSCA.sol, line 81 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjErmAkiJschIWpvJ-c:-KjErmAkiJschIWpvJ-d:b-oez7uw) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L81)):*
> ```
>   // ROSCA state
>   // Currently, we support three different types of ROSCA
>   // 0 : ROSCA where lowest bidder wins (Traditional ROSCA)
> ```

I don't think we know what's traditional, consider s/Traditional/Bidding

---

*[contracts/ROSCA.sol, line 164 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEryApUOyidBgl8VvW:-KjEryAqDCRaVNgKl57L:b-a9letd) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L164)):*
> ```
>   }
> 
>   modifier onlyTraditionalROSCA {
> ```

also here, s/traditional/bidding

---

*[contracts/ROSCA.sol, line 215 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEt2JRoJAK5AqdrtQe:-KjEt2JRoJAK5AqdrtQf:b-n63idc) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L215)):*
> ```
>       throw;
>     }
>     roscaType = roscaType_;
> ```

verify `roscaType` holds a valid value before storing it

---

*[contracts/ROSCA.sol, line 265 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEsISGCcm5yFhJcMK1:-KjEsISGCcm5yFhJcMK2:b-yq3tsk) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L265)):*
> ```
>     uint16 numUnpaidParticipants = uint16(membersAddresses.length) - (currentRound - 1);
>     // for pre-ordered ROSCA, pick the next person in the list (delinquent or not)
>     if (roscaType == 2) {
> ```

consider adding enums http://solidity.readthedocs.io/en/develop/types.html#enums to describe the rosca types, so that we're less likely to make a mistake with actual numbers. In that case we can check whether the constructor can accept an enum as well

---

*[contracts/ROSCA.sol, line 267 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEsSk35Vy6rt0gX9qO:-KjEsSk35Vy6rt0gX9qP:b47vrtg) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L267)):*
> ```
>     if (roscaType == 2) {
>       // next one in the list will always be at index 0
>       // because we unpaid members are always in the front of the list
> ```

can you enhance the explanation of this line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-:-KjEt6xc-cRgzjPefGAT:b-vs1prh)*

**Comment by shine2lay** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 20 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEsq4BhlzpLT7KaHED:-KjEuXhmsKFIpSOGiGtr:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L20)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

i think we'll want to increment the contract version, because the constructor signature has changed
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 81 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjErmAkiJschIWpvJ-c:-KjEuier8Sn7t7VnYKs_:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L81)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

I don't think we know what's traditional, consider s/Traditional/Bidding
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 164 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEryApUOyidBgl8VvW:-KjEujMORmGENboMDwvT:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L164)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

also here, s/traditional/bidding
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 215 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEt2JRoJAK5AqdrtQe:-KjExJvy39UR2qFM7YIZ:b-8jnpz6) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L215)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

verify `roscaType` holds a valid value before storing it
</blockquote></details>

i tested , if we use the enum, it'll automatically throw if you pass in invalid parameter

---

*[contracts/ROSCA.sol, line 265 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEsISGCcm5yFhJcMK1:-KjExFRltJ5VScCDqxx2:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L265)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

consider adding enums http://solidity.readthedocs.io/en/develop/types.html#enums to describe the rosca types, so that we're less likely to make a mistake with actual numbers. In that case we can check whether the constructor can accept an enum as well
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 267 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154#-KjEsSk35Vy6rt0gX9qO:-KjEvD60NyXsUUVNxuYC:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4fee8499bb3c73fe249143c222b63297d5b3eab8/contracts/ROSCA.sol#L267)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

can you enhance the explanation of this line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/154)*

**Comment by shine2lay** [comment]
@rmerom PTAL and let me know if there is anything else i need to change. if not i'll consider this as the final. i'll create another PR after tests are written to cover the new code.

**Comment by rmerom** [comment]
All looks good, thanks @shine2lay !

**Pull request closed without merging**
