### PR TITLE
Introduce Interim Fees Program

### PR DESCRIPTION
**Pull request by rmerom**
This is a stepping stone in getting to a perfect fee program.
Currently we calculate fees during contribution. However, this will result in fees being places also on over-contributions from participants, which we want to avoid.
In order to be able to extract only the required fees, we need to move to the contributions/winnings model Shine and I spoke about on slack.

This PR is therefore a stepping stone on the way to perfect fees. Therefore, the tests are also not perfect, they will be improved with the new accounting system.

As a personal note: it's quite late for me, I might have made some screwups in the code, therefore this PR might require a closer look than usual.... :) thanks.

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/50)

### CODE REVIEW

**Comment by shine2lay** [comment]
not done reviewing some files yet 

---

Reviewed 2 of 7 files at r1, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: 3 of 7 files reviewed at latest revision, 16 unresolved discussions.

---

*[contracts/ROSCA.sol, line 38 at r5](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-K_15_LSJ23FIjAyPmOH:-K_15_LSJ23FIjAyPmOI:b-z6jomd) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/509ac7b2dfb96acab27e7111a5eeec148c4e1dea/contracts/ROSCA.sol#L38)):*
> ```
>   event LogRoundNoWinner(uint256 currentRound);
>   event LogFundsWithdrawal(address user, uint256 amount);
>   // TODO(ron): rename to LogPartialWithdraw.
> ```

maybe not necessary because when the user cannot fully withdraw, it fires both LogCannotFullyWithdraw and LogRoundFundsReleased, if you still wants to update it , go for it. 

oh btw, Tom mentioned this to me a while back and i totally forgot to bring it up. He said it would be very helpful for him if we have a endOfROSCA event. WDYT?

---

*[contracts/ROSCA.sol, line 290 at r5](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-K_16w_B6UgTKSh23TAD:-K_16w_B6UgTKSh23TAE:b-f71uay) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/509ac7b2dfb96acab27e7111a5eeec148c4e1dea/contracts/ROSCA.sol#L290)):*
> ```
> 
>     uint256 tempTotalFees = totalFees;
>     totalFees = tempTotalFees;
> ```

is this necessary ? totalFees would still be totalFees even after being assigned to tempTotalFees

---

*[test/4MemberFullRoscaTest.js, line 65 at r5](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-K_18Haz7KPdR6byYiHI:-K_18Haz7KPdR6byYiHJ:bb0ok5w) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/509ac7b2dfb96acab27e7111a5eeec148c4e1dea/test/4MemberFullRoscaTest.js#L65)):*
> ```JavaScript
>   const DEFAULT_POT = CONTRIBUTION_SIZE * MEMBER_COUNT;
>   const SERVICE_FEE_IN_THOUSANDTHS = 10;
>   const NET_REWARDS_RATIO = ((1000 - SERVICE_FEE_IN_THOUSANDTHS) / 1000);
> ```

isn't it the same thing? i don't see any bug, i was just wondering why you changed it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-:-K_19lio8PSa_rul1sT_:bne2qqz)*

**Comment by shine2lay** [comment]
Reviewed 1 of 7 files at r1, 2 of 3 files at r2, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[test/utils/utils.js, line 5 at r5](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-K_1InCUH2so6XnaLbeL:-K_1InCV4A_GEsI62EmR:b-5ql6c7) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/509ac7b2dfb96acab27e7111a5eeec148c4e1dea/test/utils/utils.js#L5)):*
> ```JavaScript
> let assert = require('chai').assert;
> let consts = require("./consts.js");
> ```

i ran into errors when if i don't add "let web3 = require("web3");" this only happens if you try to run gas_check script

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50)*

**Comment by rmerom** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 38 at r5](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-K_15_LSJ23FIjAyPmOH:-K_1kysMfQqJXoxxeXMJ:b8a8f7g) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/509ac7b2dfb96acab27e7111a5eeec148c4e1dea/contracts/ROSCA.sol#L38)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

maybe not necessary because when the user cannot fully withdraw, it fires both LogCannotFullyWithdraw and LogRoundFundsReleased, if you still wants to update it , go for it. 

oh btw, Tom mentioned this to me a while back and i totally forgot to bring it up. He said it would be very helpful for him if we have a endOfROSCA event. WDYT?
</blockquote></details>

You're right, done.

---

*[contracts/ROSCA.sol, line 290 at r5](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-K_16w_B6UgTKSh23TAD:-K_1jEtTH817UI99t76i:b64wjdo) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/509ac7b2dfb96acab27e7111a5eeec148c4e1dea/contracts/ROSCA.sol#L290)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

is this necessary ? totalFees would still be totalFees even after being assigned to tempTotalFees
</blockquote></details>

yes, that's a good catch! i'm happy to report the tests have caught this too. PTAL.

---

*[test/4MemberFullRoscaTest.js, line 336 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYo-r1-336:-K_0TMAHVIV5JKMxvCdh:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/efc7e8360a91aa39df033f34ad420000a13f0f9d/test/4MemberFullRoscaTest.js#L336)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/4MemberFullRoscaTest.js, line 200 at r3](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYo-r3-200:-K_0SRx9ry9mz4f-OMy0:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/36772e0afa30f17f307bc942688e24c03038f6e4/test/4MemberFullRoscaTest.js#L200)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/4MemberFullRoscaTest.js, line 245 at r3](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYo-r3-245:-K_0SWWLMWARlTREJ6lw:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/36772e0afa30f17f307bc942688e24c03038f6e4/test/4MemberFullRoscaTest.js#L245)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/4MemberFullRoscaTest.js, line 301 at r3](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYo-r3-301:-K_0TL4yaQVGUhZdj_xz:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/36772e0afa30f17f307bc942688e24c03038f6e4/test/4MemberFullRoscaTest.js#L301)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/4MemberFullRoscaTest.js, line 309 at r3](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYo-r3-309:-K_1jnkeelca5bhl1p5k:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/36772e0afa30f17f307bc942688e24c03038f6e4/test/4MemberFullRoscaTest.js#L309)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/4MemberFullRoscaTest.js, line 65 at r5](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-K_18Haz7KPdR6byYiHI:-K_1jQLYSg3UuJ4KK-PA:b-kjch1) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/509ac7b2dfb96acab27e7111a5eeec148c4e1dea/test/4MemberFullRoscaTest.js#L65)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

isn't it the same thing? i don't see any bug, i was just wondering why you changed it
</blockquote></details>

no reason really, i wanted to change the name, and somehow found myself changing this too... :)

---

*[test/endOfROSCAUnitTest.js, line 5 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYp-r1-5:-K_1jtMEMcEMUoY0mGwo:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/efc7e8360a91aa39df033f34ad420000a13f0f9d/test/endOfROSCAUnitTest.js#L5)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

'consts' is defined but never used.
</blockquote></details>

Done.

---

*[test/endOfROSCAUnitTest.js, line 7 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYp-r1-7:-K_1juBJqw2gFnYB50-m:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/efc7e8360a91aa39df033f34ad420000a13f0f9d/test/endOfROSCAUnitTest.js#L7)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Redefinition of 'Promise'.<br>'Promise' is defined but never used.
</blockquote></details>

Done.

---

*[test/endOfROSCAUnitTest.js, line 96 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYp-r1-96:-KZzcX6Af68Hny7jRCHD:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/efc7e8360a91aa39df033f34ad420000a13f0f9d/test/endOfROSCAUnitTest.js#L96)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/endOfROSCAUnitTest.js, line 111 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYp-r1-111:-KZzcX_yHgz_YJgrfD6y:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/efc7e8360a91aa39df033f34ad420000a13f0f9d/test/endOfROSCAUnitTest.js#L111)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/withdrawUnitTest.js, line 116 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYs-r1-116:-KZzcfaO1efiCc6017v7:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/efc7e8360a91aa39df033f34ad420000a13f0f9d/test/withdrawUnitTest.js#L116)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/withdrawUnitTest.js, line 190 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYs-r1-190:-K_1jwWqaaSN98L_Nfav:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/efc7e8360a91aa39df033f34ad420000a13f0f9d/test/withdrawUnitTest.js#L190)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---

*[test/utils/consts.js, line 5 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYq-r1-5:-K_1k0r5U1kaGT9bR5Jp:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/efc7e8360a91aa39df033f34ad420000a13f0f9d/test/utils/consts.js#L5)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Missing semicolon.
</blockquote></details>

Done.

---

*[test/utils/consts.js, line 6 at r4](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-KZzcAYHerAwS--t4yYq-r4-6:-K_1k1l2TuBmjYfEDkJ6:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/74ce7df0ebbfac54b5e625559ebb428aa11b983b/test/utils/consts.js#L6)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Missing semicolon.
</blockquote></details>

Done.

---

*[test/utils/utils.js, line 5 at r5](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-K_1InCUH2so6XnaLbeL:-K_1kj_dBvF31O08E9xq:b-7vnqpl) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/509ac7b2dfb96acab27e7111a5eeec148c4e1dea/test/utils/utils.js#L5)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

i ran into errors when if i don't add "let web3 = require("web3");" this only happens if you try to run gas_check script
</blockquote></details>

I'm not getting this ,but if I add the require('web3') my tests fail...
It seems like we're not running the exact same env, let's discuss this offline (over slack/f2f) to resolve

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50)*

**Comment by shine2lay** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r6.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/50#-:-K_37JcxDBxKykcwHxIx:bnfp4nl)*

**Review by shine2lay — APPROVED** [review]

**Pull request merged**
