### PR TITLE
refactor FeeUnitsTest and 4MemberFullRoscaTest

### PR DESCRIPTION
**Pull request by shine2lay**
This PR is not yet complete , DO NOT MERGE

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/158)

### CODE REVIEW

**Comment by rmerom** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 22 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-Kjthpn0TtOzhdFwsrbJ:-Kjthpn0TtOzhdFwsrbK:bz3u2go) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L22)):*
> ```JavaScript
> 
> // Percent of the pot that winner of each round will bid
> const WINNING_BID_PERCENT = [0.95, 0.90, 1, 1];
> ```

I don't completely understand that. How can we dictate how much each winning bid will be? or maybe this is derived from DISCOUNT_BY_ROUND (in which case maybe we can have the code show that?)

---

*[test/4MemberFullRoscaTest.js, line 27 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtgkG1qxNIV_9odOoM:-KjtgkG1qxNIV_9odOoN:b-5n000x) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L27)):*
> ```JavaScript
> const WINNER_BY_ROUND = [2, 1, 0, 3];
> 
> // Individual discount
> ```

individual discount? can you elaborate?
what does each element mean?

---

*[test/4MemberFullRoscaTest.js, line 44 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-Kjti4x9NSZutyFCJqJe:-Kjti4x9NSZutyFCJqJf:b9z3g3c) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L44)):*
> ```JavaScript
> 
> // Each array represents expected user's withdrawal relative to consts.CONTRIBUTION_SIZE for each round
> const WITHDREW_PERCENT = [
> ```

s/WITHDRAW/WITHDRAWAL ?

---

*[test/4MemberFullRoscaTest.js, line 52 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtgxwUjk97TiEuIPlk:-KjtgxwUjk97TiEuIPll:b-wyd1j2) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L52)):*
> ```JavaScript
> 
> // Due to js roundoff errors, we allow values be up to a basis point off.
> function assertWeiCloseTo(actual, expected) {
> ```

consider renaming this and changing the comment:
1. it doesn't really have to do with Wei, I think.
2. s/basis point/ETH basis point (or just 0.0001 ETH)

---

*[test/4MemberFullRoscaTest.js, line 70 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-Kjti9t_aaIW5g8RMG7T:-Kjti9t_aaIW5g8RMG7U:b-ri5a29) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L70)):*
> ```JavaScript
> function checkForDelinquencyForUserInRound(userIndex, roundNum) {
>   let expectedCredit = expectedCreditToDate(userIndex, roundNum)
>   let totalDiscountToRoundNum = 0
> ```

nit: consider s/totalDiscoundtoRoundNum/totalDiscount to help readability

---

*[test/4MemberFullRoscaTest.js, line 80 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtiHNwskPUcDG7IGu8:-KjtiHNwskPUcDG7IGu9:b-be7w0a) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L80)):*
> ```JavaScript
> }
> 
> function expectedTotalFeesUpToRound (roundNum) {
> ```

extra space before (

---

*[test/4MemberFullRoscaTest.js, line 105 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtiXUY4AX8wiLYHHVM:-KjtiXUY4AX8wiLYHHVN:bqygvr5) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L105)):*
> ```JavaScript
> }
> 
> contract('Full 4 Member ROSCA Test', function(accounts) {
> ```

(ignore this comment) reviewed up to here right now, will continue later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158)*

**Comment by blorange** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 13 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtkGMMclO0bJZvFPTL:-KjtkGMMclO0bJZvFPTM:bwiyg7v) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L13)):*
> ```JavaScript
> let ExampleToken = artifacts.require('test/ExampleToken.sol');
> let consts = require('./utils/consts');
> let ROSCAHelper = require('./utils/roscaHelper')
> ```

Can we put the same eslint rules on this repo as on `wetrust-site` and `rosca-mvp`?

---

*[test/4MemberFullRoscaTest.js, line 120 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtoDyDqknv2iMMjRIH:-KjtoDyDqknv2iMMjRII:b-c5vyz3) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L120)):*
> ```JavaScript
>   // C is the consts.CONTRIBUTION_SIZE
>   // P is the consts.defaultPot()
>   // MC is consts.memberCount() == 4
> ```

Confused why we have a method for something which always returns 4?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158)*

**Comment by blorange** [comment]
It looks good - I got a little confused seeing things like `rosca.withdraw(2)` for the first time, as it's not clear that the var `rosca` in that context is a helper object "wrapping" the contract instance. It becomes increasingly confusing in the roscaHelper file where the var `rosca` _is_ a contract instance.

Maybe going between `roscaContract` and `roscaHelper` would make things a little less confusing, 

---

Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 145 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-Kjtp-u-FXHWpqRfR01G:-Kjtp-u-FXHWpqRfR01H:b-7fg3wo) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L145)):*
> ```JavaScript
>     yield rosca.bid(2, consts.defaultPot()); // lowestBid = pot, winner = 2
>     // foreperson should be allowed to withdraw the extra C * 9, new credit = contributionSize
>     yield rosca.rosca.withdraw(0);  // p0 withdraws overcontributions, credit should be C again
> ```

`rosca.rosca`? Another example of this a few lines down

---

*[test/4MemberFullRoscaTest.js, line 190 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtpxDFAg1vz79jiEbJ:-KjtpxDFAg1vz79jiEbK:b-wzpuz6) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L190)):*
> ```JavaScript
>     // we check how much was withdrawn indirectly, by checking how much contract's balance was reduced,
>     // to avoid factoring in gas costs paid by p2.
>     /* let expectedWithdrawalBalance = utils.afterFee(consts.defaultPot() * WINNING_BID_PERCENT[0]) -
> ```

Can we get rid of the commented out line if we're not using it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-:-KjtyQ7lsXbGW2VjZGlr:b-as7x5q)*

**Comment by shine2lay** [comment]
okay, i can see how it can be confusing, i'll change it accordingly 

---

Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 190 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtpxDFAg1vz79jiEbJ:-KkXAhbhDgje7Zf80qOe:b-xm3gyq) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L190)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

Can we get rid of the commented out line if we're not using it?
</blockquote></details>

ok, i'll comb thru the file once more and clean up the comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-:-KkXAGHVZ_DFqSGLCGEX:b73aeq5)*

**Comment by shine2lay** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 13 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtkGMMclO0bJZvFPTL:-KkXRVXFDsbSdcUBTrOd:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L13)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

Can we put the same eslint rules on this repo as on `wetrust-site` and `rosca-mvp`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158)*

**Comment by shine2lay** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 80 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtiHNwskPUcDG7IGu8:-KkXRppRm4HqZXn2MuNU:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L80)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

extra space before (
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158)*

**Comment by shine2lay** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 70 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-Kjti9t_aaIW5g8RMG7T:-KkXSGit56zwfFMwsWTj:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L70)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

nit: consider s/totalDiscoundtoRoundNum/totalDiscount to help readability
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158)*

**Comment by shine2lay** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 22 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-Kjthpn0TtOzhdFwsrbJ:-KkXUGYOk5UNGV0t7DuI:bccptfq) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L22)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

I don't completely understand that. How can we dictate how much each winning bid will be? or maybe this is derived from DISCOUNT_BY_ROUND (in which case maybe we can have the code show that?)
</blockquote></details>

these are bids (% to the pot) placed by winners of each round. every other bids in each round is derived from these number. I still thinks this test is not as robust as i want it to yet, i want to spend some more time making it more robust.

---

*[test/4MemberFullRoscaTest.js, line 44 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-Kjti4x9NSZutyFCJqJe:-KkXSlBACtDcyYEZEzr8:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L44)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

s/WITHDRAW/WITHDRAWAL ?
</blockquote></details>

Done.

---

*[test/4MemberFullRoscaTest.js, line 52 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtgxwUjk97TiEuIPlk:-KkXUCPLzNG4jsjm_HUa:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L52)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

consider renaming this and changing the comment:
1. it doesn't really have to do with Wei, I think.
2. s/basis point/ETH basis point (or just 0.0001 ETH)
</blockquote></details>

Done.

---

*[test/4MemberFullRoscaTest.js, line 105 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtiXUY4AX8wiLYHHVM:-KkXTlvuUOJwIzYnkQdS:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L105)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

(ignore this comment) reviewed up to here right now, will continue later
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158)*

**Comment by shine2lay** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 120 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtoDyDqknv2iMMjRIH:-KkXVivYQL5eHchE_LOf:b-5inft4) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L120)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

Confused why we have a method for something which always returns 4?
</blockquote></details>

my mistake during refactoring

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158)*

**Comment by shine2lay** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 145 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-Kjtp-u-FXHWpqRfR01G:-KkXbYrdHW0b49GLOq6E:bi19xlu) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L145)):*
<details><summary><i>Previously, blorange (Brian Loranger) wrote…</i></summary><blockquote>

`rosca.rosca`? Another example of this a few lines down
</blockquote></details>

another mistake during refactoring, thanks for catching this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158)*

**Comment by shine2lay** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 27 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158#-KjtgkG1qxNIV_9odOoM:-KkXdIOqFgiUp0iy7_w3:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/a0b80489c061bef41f33c5dec22f1fc309050f68/test/4MemberFullRoscaTest.js#L27)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

individual discount? can you elaborate?
what does each element mean?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/158)*

**Pull request merged**
