### PR TITLE
Tests for ERC20 support (see details inside)

### PR DESCRIPTION
**Pull request by rmerom**
- Renames `ROSCA.sol` to `older/ROSCAv1.sol`
- Renames (and fixes) `tokenableROSCA.sol` to `ROSCA.sol`
- Improves 4MemberFullRoscaTest to test twice: once for ETH contract, and once for ERC20 contract (same scenario for both)
- As ROSCA constructor receives one extra param, changes all occurences of constructor throughout the tests.

Still TODO:
- Specific tests for `contribute` and `withdraw`. Optionally also for `endOfROSCARetrieveSurplus` and `endOfROSCARetrieveFees`

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/137)

### CODE REVIEW

**Comment by morelazers** [comment]
Review status: 0 of 21 files reviewed at latest revision, 9 unresolved discussions.

---

*[contracts/ROSCA.sol, line 31 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerOkls2BueW4s2ayfF:-KerOkls2BueW4s2ayfG:bub6do6) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L31)):*
> ```
> 
>   // Start time of the ROSCA must be at least this much time ahead of when the ROSCA is created
>   uint32 constant internal MINIMUM_TIME_BEFORE_ROSCA_START = 1 days;
> ```

What's the reason for changing this back to a day?

---

*[contracts/ROSCA.sol, line 59 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerOqf-L-fHqwC8hz-W:-KerOqf-L-fHqwC8hz-X:b-nezx1q) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L59)):*
> ```
>   // this event with the actual amount released, if send() is successful.
>   event LogCannotWithdrawFully(uint256 creditAmount);
>   event LogUnsuccessfulBid(address bidder,uint256 bid, uint256 lowestBid);
> ```

Nit: inconsistent spacing in event args

---

*[contracts/ROSCA.sol, line 395 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerPtpPyXfm6n3sGfi2:-KerPtpQi1RrtbyH_WeV:b7mk927) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L395)):*
> ```
>    * + New bid is lower than the lowest bid so far.
>    */
>   function bid(uint256 bid) onlyFromMember roscaNotEnded onlyIfEscapeHatchInactive external {
> ```

I think we should rename the modifiers. We have `onlyFromMember`, `onlyIfEscapeHatchInactive` and `roscaNotEnded`. Either the last one should be `onlyIfRoscaNotEnded`, or we should remove the `onlyIf` from all of them and have the modifiers be `fromMember`, `roscaNotEnded` and `escapeHatchInactive`.

Wdyt?

---

*[contracts/ROSCA.sol, line 542 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerRGqt1F5N9df5HG__:-KerRGquktlqTfozP_A1:bnfvt9w) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L542)):*
> ```
>       totalFees = tempTotalFees;
>     } else {
>       LogFeesWithdrawal(totalFees);
> ```

This will always log 0

---

*[contracts/ROSCA.sol, line 575 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerRYDqznnN0p6rb63N:-KerRYDrTZCpv3na_fZd:bmect23) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L575)):*
> ```
>     LogEmergencyWithdrawalPerformed(getBalance());
>     // Send everything, including potential fees, to foreperson to disperse offline to participants.
>     selfdestruct(foreperson);
> ```

I don't think this will send any ERC20s, we need a check for isEthRosca here, then a tokenContract.transfer to the foreperson if not

---

*[contracts/older/ROSCAv1.sol, line 1 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerSL8YLjcnE1LCqvhA:-KerSL8Zoe5Y89t1dCCs:b-yy826z) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/older/ROSCAv1.sol#L1)):*
> ```
> pragma solidity ^0.4.4;
> ```

I didn't review this file, since it looks like a reversion to before we started the ERC20 work. If you would like me to review anyway let me know.

---

*[migrations/3_deploy_test_contract.js, line 9 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerSs444eZMlNEpWCrw:-KerSs444eZMlNEpWCrx:b-lgxug5) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/migrations/3_deploy_test_contract.js#L9)):*
> ```JavaScript
>     deployer.deploy(ROSCATest, 0 /* use ETH */, 3, 1e16 , simulatedTimeNow + (86400 + 10) ,
>         [accounts[1],accounts[2],accounts[3]], 2);
>     deployer.deploy(ExampleToken);
> ```

We deploy the example token but we're specifying that we want an ETH ROSCA is that correct?

---

*[test/4MemberFullRoscaTest.js, line 100 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerUCS217E33Lg8fs6b:-KerUCS217E33Lg8fs6c:b-3yp7oo) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/test/4MemberFullRoscaTest.js#L100)):*
> ```JavaScript
>     let blockTime = latestBlock.timestamp;
>     ROSCATest.new(
>       0 /* ERC20 address */, ROUND_PERIOD_IN_DAYS, CONTRIBUTION_SIZE, blockTime + MIN_START_DELAY,
> ```

Worth giving this a constant? e.g. ETH_ROSCA_TOKEN_ADDRESS

---

*[test/4MemberFullRoscaTest.js, line 108 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerUdAQVqgARciJKNf3:-KerUdARuAF-qKovUh03:b-a6l0rv) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/test/4MemberFullRoscaTest.js#L108)):*
> ```JavaScript
>             tokenRosca = {rosca: bRosca, tokenContract: ExampleToken.deployed()};
> 
>             currentRosca = ethRosca;
> ```

Is there a way we can use a queue-type system? Deploy a bunch of ROSCAs, specify the tests we want to run for each one, then process each queue item one by one?

Just a thought, might be pointless amounts of work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137)*

**Comment by rmerom** [comment]
Thank you for a through review, it's like a good cold shower...

---

Review status: 0 of 21 files reviewed at latest revision, 9 unresolved discussions.

---

*[contracts/ROSCA.sol, line 31 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerOkls2BueW4s2ayfF:-Ket06Nf-JaMO7zijah0:b8vwy64) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L31)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

What's the reason for changing this back to a day?
</blockquote></details>

Good question. I have no idea how this happened. Done.

---

*[contracts/ROSCA.sol, line 59 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerOqf-L-fHqwC8hz-W:-Ket0E_Y7HQS7Co5cAcT:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L59)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

Nit: inconsistent spacing in event args
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 395 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerPtpPyXfm6n3sGfi2:-Ket0StKULtu1yZQX_zv:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L395)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

I think we should rename the modifiers. We have `onlyFromMember`, `onlyIfEscapeHatchInactive` and `roscaNotEnded`. Either the last one should be `onlyIfRoscaNotEnded`, or we should remove the `onlyIf` from all of them and have the modifiers be `fromMember`, `roscaNotEnded` and `escapeHatchInactive`.

Wdyt?
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 542 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerRGqt1F5N9df5HG__:-Ket0aZq7ZxPsal8VPdb:b-nqafhs) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L542)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

This will always log 0
</blockquote></details>

Good catch! done.

---

*[contracts/ROSCA.sol, line 575 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerRYDqznnN0p6rb63N:-Ket1IWuMPh5kIESRY3y:bv7sfub) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L575)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

I don't think this will send any ERC20s, we need a check for isEthRosca here, then a tokenContract.transfer to the foreperson if not
</blockquote></details>

Another good catch! done.

---

*[contracts/older/ROSCAv1.sol, line 1 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerSL8YLjcnE1LCqvhA:-Ket1LJpq_qsPN5jdGvS:b-jeslk) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/older/ROSCAv1.sol#L1)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

I didn't review this file, since it looks like a reversion to before we started the ERC20 work. If you would like me to review anyway let me know.
</blockquote></details>

That's true.

---

*[migrations/3_deploy_test_contract.js, line 9 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerSs444eZMlNEpWCrw:-Ket1SuiWOnzn-xTYG_w:b-c55hqw) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/migrations/3_deploy_test_contract.js#L9)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

We deploy the example token but we're specifying that we want an ETH ROSCA is that correct?
</blockquote></details>

We need this in order for the tests to work, I guess it generates ExampleToken.sol.js . ...

---

*[test/4MemberFullRoscaTest.js, line 100 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerUCS217E33Lg8fs6b:-Ket1_VSOw29Zi-Zho0P:bp9syt4) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/test/4MemberFullRoscaTest.js#L100)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

Worth giving this a constant? e.g. ETH_ROSCA_TOKEN_ADDRESS
</blockquote></details>

I feel using 0 (as opposed to other magic numbers), with a short comment can sometimes be more readable than names, esp. that 0 isn't really an address. However, I don't have a strong opinion about it, if you think it's important I'll change.

---

*[test/4MemberFullRoscaTest.js, line 108 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerUdAQVqgARciJKNf3:-Ket1qrXcE1JICNCaVqg:bx8zp4m) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/test/4MemberFullRoscaTest.js#L108)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

Is there a way we can use a queue-type system? Deploy a bunch of ROSCAs, specify the tests we want to run for each one, then process each queue item one by one?

Just a thought, might be pointless amounts of work.
</blockquote></details>

I think it would be worth it if we had several ROSCAs. Otherwise, I see myself spending a nice amount of time just debugging the queue... :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-:-Ket2RXSRPqbCWnbLXT-:b-uot93h)*

**Comment by morelazers** [comment]
Review status: 0 of 21 files reviewed at latest revision, 5 unresolved discussions.

---

*[contracts/ROSCA.sol, line 395 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerPtpPyXfm6n3sGfi2:-KethWJEGf8M8xuvnREW:b-njyhds) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L395)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See above comment regarding casing

---

*[contracts/ROSCA.sol, line 141 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KetgMvU7bKJqrsNADJA:-KetgMvU7bKJqrsNADJB:bk6kiuv) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7e44bcc2a7733184b2bf8983c7d3d79bba7ffca6/contracts/ROSCA.sol#L141)):*
> ```
>   }
> 
>   modifier OnlyIfRoscaEnded {
> ```

Is there a reason we went from lower camelCase to upper CamelCase?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137)*

**Comment by rmerom** [comment]
Review status: 0 of 21 files reviewed at latest revision, 5 unresolved discussions.

---

*[contracts/ROSCA.sol, line 395 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KerPtpPyXfm6n3sGfi2:-KetjmYTFQPCPUY1zSXo:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/4557eeb0f84b029ea973e72533c5baa5e3b5ec09/contracts/ROSCA.sol#L395)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

See above comment regarding casing
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 141 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-KetgMvU7bKJqrsNADJA:-KetjjMYHEd4bVYm0KCp:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7e44bcc2a7733184b2bf8983c7d3d79bba7ffca6/contracts/ROSCA.sol#L141)):*
<details><summary><i>Previously, morelazers (Tom Nash) wrote…</i></summary><blockquote>

Is there a reason we went from lower camelCase to upper CamelCase?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137)*

**Comment by morelazers** [comment]
:lgtm:

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/137#-:-KeyH1cNW3Jd8s12zaR8:bnfp4nl)*

**Review by morelazers — APPROVED** [review]

**Pull request merged**
