### PR TITLE
fix getParticipantBalance to show proper values.

### PR DESCRIPTION
**Pull request by shine2lay**
getParticipantBalance doesn't show proper values for users in "debt" after the endofROSCA

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/111)

### CODE REVIEW

**Comment by shine2lay** [comment]
please publish a new version of contract after merging

**Review by rmerom — COMMENTED** [review]
Good that you caught this edge case!
At end of ROSCA, shouldn't a delinquent participant be able to withdraw only his contributions, not his entire credit?

Also would be great, though not completely required, to add a test to getParticipantBalance that covers this case.

**Comment by shine2lay** [comment]
well, this fix wouldn't allow user to withdraw his entire credit.
we can ignore this line because, at the endofROSCA, 

``` totalDebit = int256(currentRound * contributionSize); ```
would be the same as Default pot, the return value should be contributions

**Comment by rmerom** [comment]
You're right!
As this is not completely intuitive (the fact that the winning will zero out the debit), can we add a comment to that effect?

**Review by rmerom — APPROVED** [review]

**Pull request merged**
