### PR TITLE
allow foreperson to retrieve funds a certain period of time after ROS…

### PR DESCRIPTION
**Pull request by rmerom**
…CA ends + some cleanup

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/21)

### CODE REVIEW

**Comment by shine2lay** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[contracts/ROSCA.sol, line 28 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21#-KZ-XuA7ilEtGv-laiuA:-KZ-XuA7ilEtGv-laiuB:b-prkrhf) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/bf0ad03d44c5c909150d5837d5e98ec884352147/contracts/ROSCA.sol#L28)):*
> ```
>   // Foreperson may collect the remaining contract funds this amount of time
>   // after the ROSCA ends.
>   uint256 constant COLLECTION_DEADLINE = 10 days;
> ```

What do you think about using roundPeriod as a deadline, for example, after endOfROSCA, the user have exactly one roundPeriod to collect the withdrawal and after that the foreman can kill the contract

---

*[contracts/ROSCA.sol, line 154 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21#-KZ-ZRDVOvrKvoB1kup-:-KZ-ZRDWIln--JIqiY-g:b-yh9az8) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/bf0ad03d44c5c909150d5837d5e98ec884352147/contracts/ROSCA.sol#L154)):*
> membersAddresses[(semi_random + i) % membersAddresses.length]

this is something i forgot, this should be replaced with candidate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21)*

**Comment by rmerom** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[contracts/ROSCA.sol, line 28 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21#-KZ-XuA7ilEtGv-laiuA:-KZ-i8--ArVzwxfpscw2:b1imvfr) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/bf0ad03d44c5c909150d5837d5e98ec884352147/contracts/ROSCA.sol#L28)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

What do you think about using roundPeriod as a deadline, for example, after endOfROSCA, the user have exactly one roundPeriod to collect the withdrawal and after that the foreman can kill the contract
</blockquote></details>

Hmm that's an interesting idea. I can't think of a very strong to use either approach. Do you think it's better to use the extra round time? If so, I'll change it accordingly.

---

*[contracts/ROSCA.sol, line 154 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21#-KZ-ZRDVOvrKvoB1kup-:-KZ-igEToDhdmpgHspoX:be3e1v3) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/bf0ad03d44c5c909150d5837d5e98ec884352147/contracts/ROSCA.sol#L154)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

> membersAddresses[(semi_random + i) % membersAddresses.length]

this is something i forgot, this should be replaced with candidate

</blockquote></details>

right! if you don't mind, just for cleanliness I'll create a separate PR for that and send you shortly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21)*

**Comment by shine2lay** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[contracts/ROSCA.sol, line 28 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21#-KZ-XuA7ilEtGv-laiuA:-KZ-jlsAWRxgSC0K71-_:b-8tqja9) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/bf0ad03d44c5c909150d5837d5e98ec884352147/contracts/ROSCA.sol#L28)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

Hmm that's an interesting idea. I can't think of a very strong to use either approach. Do you think it's better to use the extra round time? If so, I'll change it accordingly.
</blockquote></details>

i think that would be better choice because all the other round winner have one round Period to withdraw before anyone else could get a shot at it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21)*

**Comment by rmerom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[contracts/ROSCA.sol, line 28 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21#-KZ-XuA7ilEtGv-laiuA:-KZ-lEY-0l4Y3nRENG4s:b-oq3912) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/bf0ad03d44c5c909150d5837d5e98ec884352147/contracts/ROSCA.sol#L28)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

i think that would be better choice because all the other round winner have one round Period to withdraw before anyone else could get a shot at it
</blockquote></details>

Done, PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21)*

**Comment by shine2lay** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/21#-:-KZ-m-lUCPCHY4aXXewk:bnfp4nl)*

**Review by shine2lay — APPROVED** [review]

**Pull request merged**
