### PR TITLE
Script for checking gas used in ROSCA

### PR DESCRIPTION
**Pull request by rmerom**
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/35)

### CODE REVIEW

**Comment by rmerom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 18 unresolved discussions.

---

*[test/utils/utils.js, line 5 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/35#-KZbRHdGclLtCmfuahaM-r1-5:-KZc_b19QcPUaeXNV43U:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/9d851ede930bba9a1f658b153c447b35b5df8a30/test/utils/utils.js#L5)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.<br>Expected '===' and instead saw '=='.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/35)*

**Comment by rmerom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 19 unresolved discussions.

---

*[test/utils/utils.js, line 5 at r3](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/35#-KZbRHdGclLtCmfuahaM-r3-5:-KZcaTH5JfV1tgBJIiVh:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/389063cb73e7e4fe26c353731798efafb253d8e7/test/utils/utils.js#L5)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/35)*

**Comment by shine2lay** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 20 unresolved discussions.

---

*[test/utils/utils.js, line 4 at r4](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/35#-KZhBgmAJqnX8I0mOzfp:-KZhBgmAJqnX8I0mOzfq:brikn1j) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/c36775d16ba6b5a21ac6caa5517e7e17cdd1c3a9/test/utils/utils.js#L4)):*
> ```JavaScript
> 
> let assert = require('chai').assert;
> ```

i had to add "let web3 = require('web3'); to run successfully

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/35#-:-KZhBc7J2sbLXzuR_ggn:bnfp4nl)*

**Review by shine2lay — APPROVED** [review]

**Comment by rmerom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 20 unresolved discussions.

---

*[test/utils/utils.js, line 4 at r4](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/35#-KZhBgmAJqnX8I0mOzfp:-KZhD3HDweZtR_GrOD3V:b-cd0rhz) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/c36775d16ba6b5a21ac6caa5517e7e17cdd1c3a9/test/utils/utils.js#L4)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

i had to add "let web3 = require('web3'); to run successfully
</blockquote></details>

this doesn't work for me in the script, that's why i add to add this workaround. if you see something breaks on your side, let me know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/35)*

**Pull request merged**
