### PR TITLE
Explicitly define assert to silence Hound

### PR DESCRIPTION
**Pull request by rmerom**
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/27)

### CODE REVIEW

**Comment by shine2lay** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27)*

**Comment by shine2lay** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/startRoundUnitTest.js, line 3 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27#-KZN7R1s2iEIN3l-ThfP-r1-3:-KZNlu_aJ2D_vfoEBGet:b22mmp) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/8468ad337b6f9c3ab952a768ef165770e7c9c908/test/startRoundUnitTest.js#L3)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Bad line breaking before ','.
</blockquote></details>

Are you planning to fix these warning ? or do we ignore these?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27)*

**Comment by rmerom** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/startRoundUnitTest.js, line 3 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27#-KZN7R1s2iEIN3l-ThfP-r1-3:-KZNr01Xib2aJzoDmv36:b-vjuyxm) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/8468ad337b6f9c3ab952a768ef165770e7c9c908/test/startRoundUnitTest.js#L3)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

Are you planning to fix these warning ? or do we ignore these?
</blockquote></details>

yes, i think you were looking at an older version

---

*[test/startRoundUnitTest.js, line 4 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27#-KZN7R1s2iEIN3l-ThfP-r1-4:-KZNr6GOqcs339axNQhk:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/8468ad337b6f9c3ab952a768ef165770e7c9c908/test/startRoundUnitTest.js#L4)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Comma warnings can be turned off with 'laxcomma'.<br>Bad line breaking before ','.<br>'expect' is defined but never used.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27)*

**Comment by shine2lay** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/addMemberUnitTest.js, line 3 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27#-KZN7R1s2iEIN3l-ThfN-r2-3:-KZNrxXCmW8DsUobIyG7:b7nnobi) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/3112f531e0b6619c4d2b3a8eeffd4fd743a7222a/test/addMemberUnitTest.js#L3)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

'expect' is defined but never used.
</blockquote></details>

expect is still defined? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27)*

**Comment by rmerom** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/addMemberUnitTest.js, line 3 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27#-KZN7R1s2iEIN3l-ThfN-r2-3:-KZOHTK_Sd7Iqh5YrMDU:b4y3f4o) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/3112f531e0b6619c4d2b3a8eeffd4fd743a7222a/test/addMemberUnitTest.js#L3)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

expect is still defined? 
</blockquote></details>

My thinking was that for simplicity we'll use this same header in every file, regardless of where we use assert and where we use except. Does that make sense to you? otherwise, I can remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27)*

**Comment by shine2lay** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/addMemberUnitTest.js, line 3 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27#-KZN7R1s2iEIN3l-ThfN-r2-3:-KZP0fcReS4HXdG9k8V1:b4xus14) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/3112f531e0b6619c4d2b3a8eeffd4fd743a7222a/test/addMemberUnitTest.js#L3)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

My thinking was that for simplicity we'll use this same header in every file, regardless of where we use assert and where we use except. Does that make sense to you? otherwise, I can remove it.
</blockquote></details>

I have not used except in any of the test files, if you have plans on using it then i agree, we should leave it, i'll go ahead and approve it so you can merge it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/27)*

**Review by shine2lay — APPROVED** [review]

**Comment by rmerom** [comment]
Explicitly define assert to silence Hound

**Pull request merged**
