### PR TITLE
added getBalance() + UnitTests

### PR DESCRIPTION
**Pull request by shine2lay**
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/91)

### CODE REVIEW

**Comment by rmerom** [comment]
Review status: 0 of 3 files reviewed at latest revision, 15 unresolved discussions.

---

*[contracts/ROSCA.sol, line 406 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5KjpToLg9BDJqBWzk:-Ka5KjpToLg9BDJqBWzl:b2dovj6) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/contracts/ROSCA.sol#L406)):*
> ```
> 
>   /**
>    * Allows the user to check the amount they can withdraw if the return value is positive
> ```

consider:
Returns how much a user can withdraw (positive return value), or how much they need to contribute to be in good standing (negative return value).

---

*[contracts/ROSCA.sol, line 409 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5L0gHBoQfJBPiyTcL:-Ka5L0gHBoQfJBPiyTcM:bdqci7k) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/contracts/ROSCA.sol#L409)):*
> ```
>    * negative return value represent amount that user must contribute in to be in goodStanding
>    */
>   function getBalance(address user) onlyFromMember external returns(int256 withdrawable) {
> ```

no need for the return variable name ("withdrawable")

---

*[test/cleanUpPreviousRoundUnitTest.js, line 108 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5LU0NXmoikcvKJZJi:-Ka5LU0NXmoikcvKJZJj:bs1l5kj) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/cleanUpPreviousRoundUnitTest.js#L108)):*
> ```JavaScript
>     }));
> 
>     it("checks if random unpaid member is picked when no bid was placed and" +
> ```

i'm not sure the name of the test is still true?
consider "when no one bids, checks that non-delinquent members are preferred, but delinquent members can win when only they are eligible".

Also, can this test be merged with "checks if random unpaid member in good Standing is picked when no bid was placed"? they seem to overlap alot.

---

*[test/cleanUpPreviousRoundUnitTest.js, line 110 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5LIJpDZFrMZlzXZJj:-Ka5LIJpDZFrMZlzXZJk:bdb3dil) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/cleanUpPreviousRoundUnitTest.js#L110)):*
> ```JavaScript
>     it("checks if random unpaid member is picked when no bid was placed and" +
>         "only delinquent members are eligible", co(function* () {
>         // 3 member rosca, where only p1 is the only one in goodStanding and will win the Pot in round 1
> ```

two "only"

---

*[test/getBalanceUnitTest.js, line 8 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5Odc8UZBa_e-2DL0B:-Ka5Odc8UZBa_e-2DL0C:b-h0xyut) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L8)):*
> ```JavaScript
> let utils = require("./utils/utils.js");
> 
> contract('ROSCA getBalance Unit Test', function(accounts) {
> ```

general comment:
the tests here "prove" get getBalance works by calling withdraw() after calling getBalance with some mathematical wizardry and expecting the withdrawn value to be correct.
While this is true, i think it adds some mental load to understanding the tests. Is there a reason why we can't simply assert what getBalance should return?

---

*[test/getBalanceUnitTest.js, line 41 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5MUpFtll0n5ItxhCJ:-Ka5MUpFtll0n5ItxhCK:b-2s83on) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L41)):*
> ```JavaScript
>         let balance = yield rosca.getBalance.call(accounts[2]);
> 
>         // expectedBalance is Pot won - nextRound contribution (contributionSize + totalDiscount)
> ```

can we add an assert that the balance is positive?

---

*[test/getBalanceUnitTest.js, line 50 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5MZmkUhObjlb0I7Kl:-Ka5MZmkUhObjlb0I7Km:b-mei5cv) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L50)):*
> ```JavaScript
>     }));
> 
>     it("checks that getBalance returns negative Value for delinquents(who haven't won the Pot)", co(function* () {
> ```

space before ( in ""

---

*[test/getBalanceUnitTest.js, line 58 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5OKu8foWKE8KM1PKL:-Ka5OKu8foWKE8KM1PKM:b9d5536) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L58)):*
> ```JavaScript
> 
>         // get the balance of delinquent who haven't won the Pot
>         // test by calling withdrawing, which should throw and
> ```

s/withdrawing/withdraw

---

*[test/getBalanceUnitTest.js, line 61 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5MnRr8pppnnQ3F4a-:-Ka5MnRr8pppnnQ3F4a0:bfrerzp) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L61)):*
> ```JavaScript
>         // make contribution > than balance, and call withdraw
> 
>         let balance = (yield rosca.getBalance.call(accounts[1]));
> ```

let's assert that balance is negative?

---

*[test/getBalanceUnitTest.js, line 64 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5NJkU-gPk7JiFQSfc:-Ka5NJkU-gPk7JiFQSfd:b1tzx39) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L64)):*
> ```JavaScript
>         utils.assertThrows(rosca.withdraw({from: accounts[1]}));
>         // contributed extra by CONTRIBUTION_SIZE, when we try to withdraw, we should get CONTRIBUTION_SIZE
>         yield rosca.contribute({from: accounts[1], value: (CONTRIBUTION_SIZE - balance)});
> ```

The test is functionally correct, but it took me some time to understand. 

Perhaps it would be easier to understand the test if we define
```
let EXTRA_CONTRIBUTION = <something>;
```

then:
```
let debt = -balance;

 yield rosca.contribute({from: accounts[1], value: (debt  + EXTRA_CONTRIBUTION)});
```
and check the withdrawal to be EXTRA_CONTRIBUTION?

---

*[test/getBalanceUnitTest.js, line 72 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5NnxjMtPMKsuOCiuk:-Ka5NnxjMtPMKsuOCiul:b-mei5cv) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L72)):*
> ```JavaScript
>     }));
> 
>     it("checks that getBalance returns negative Value for delinquents(who already won the Pot)", co(function* () {
> ```

space before ( in ""

---

*[test/getBalanceUnitTest.js, line 80 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5O1y3LU5LCAnFufm1:-Ka5O1y3LU5LCAnFufm2:b-15gu8l) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L80)):*
> ```JavaScript
>             rosca.startRound(),
>             rosca.contribute({from: accounts[0], value: 5 * CONTRIBUTION_SIZE}),
>             rosca.contribute({from: accounts[1], value: 0.5 * CONTRIBUTION_SIZE}),
> ```

do you think it's possible to make the ROSCA with less participants, thus making the test smaller and easier to follow?

---

*[test/getBalanceUnitTest.js, line 99 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5OA8potqDvNnQbYoG:-Ka5OA8qPlHh2B6a-2jk:bmbgiv5) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L99)):*
> ```JavaScript
> 
>         utils.increaseTime(ROUND_PERIOD_DELAY);
>         yield rosca.startRound();
> ```

i suggest adding a comment that at this point we expect one of the delinquents to win.

---

*[test/getBalanceUnitTest.js, line 103 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5ONNXh2vlqMZAJ7og:-Ka5ONNXh2vlqMZAJ7oh:b-vsjhab) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L103)):*
> ```JavaScript
>         yield Promise.delay(500);
>         assert.isOk(eventFired);
>         // get the balance of delinquent who haven't won the Pot
> ```

s/haven't/has

---

*[test/getBalanceUnitTest.js, line 104 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5OMtoOA-U2m0aVlvJ:-Ka5OMtoOA-U2m0aVlvK:b9d5536) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L104)):*
> ```JavaScript
>         assert.isOk(eventFired);
>         // get the balance of delinquent who haven't won the Pot
>         // test by calling withdrawing, which should throw and
> ```

s/withdrawing/withdraw

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91)*

**Comment by shine2lay** [comment]
Review status: 0 of 3 files reviewed at latest revision, 15 unresolved discussions.

---

*[contracts/ROSCA.sol, line 406 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5KjpToLg9BDJqBWzk:-Ka8WASWTCdyIqNoZ3Cg:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/contracts/ROSCA.sol#L406)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

consider:
Returns how much a user can withdraw (positive return value), or how much they need to contribute to be in good standing (negative return value).
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 409 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5L0gHBoQfJBPiyTcL:-Ka8WB2OWWtvnVu-O27w:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/contracts/ROSCA.sol#L409)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

no need for the return variable name ("withdrawable")
</blockquote></details>

Done.

---

*[test/cleanUpPreviousRoundUnitTest.js, line 108 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5LU0NXmoikcvKJZJi:-Ka8WNV4mUMwRLrDfk7c:bh0u4b4) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/cleanUpPreviousRoundUnitTest.js#L108)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

i'm not sure the name of the test is still true?
consider "when no one bids, checks that non-delinquent members are preferred, but delinquent members can win when only they are eligible".

Also, can this test be merged with "checks if random unpaid member in good Standing is picked when no bid was placed"? they seem to overlap alot.
</blockquote></details>

if we merge it, test will become a significantly long, I am sure you would agree that long test is a lot harder to catch bug and maintain.

---

*[test/cleanUpPreviousRoundUnitTest.js, line 110 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5LIJpDZFrMZlzXZJj:-Ka8Wp5resf71nf9lsHF:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/cleanUpPreviousRoundUnitTest.js#L110)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

two "only"
</blockquote></details>

Done.

---

*[test/getBalanceUnitTest.js, line 8 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5Odc8UZBa_e-2DL0B:-Ka8WsY5HJLWinS3UOSd:b9qyn4c) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L8)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

general comment:
the tests here "prove" get getBalance works by calling withdraw() after calling getBalance with some mathematical wizardry and expecting the withdrawn value to be correct.
While this is true, i think it adds some mental load to understanding the tests. Is there a reason why we can't simply assert what getBalance should return?
</blockquote></details>

Correct me if I am wrong, you said it would be better to test behaviorally. 
I thought calling withdraw proves that getBalance returns the correct pending withdrawal.
That's why i decide to use withdraw instead of checking the return value with expected value. 

---

*[test/getBalanceUnitTest.js, line 41 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5MUpFtll0n5ItxhCJ:-Ka8Yvm47AHrS880ad1O:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L41)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

can we add an assert that the balance is positive?
</blockquote></details>

Done.

---

*[test/getBalanceUnitTest.js, line 50 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5MZmkUhObjlb0I7Kl:-Ka8Z4jnLRAP7o07IvYV:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L50)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

space before ( in ""
</blockquote></details>

Done.

---

*[test/getBalanceUnitTest.js, line 58 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5OKu8foWKE8KM1PKL:-Ka8Z87GQY3hf7yDb5uU:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L58)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

s/withdrawing/withdraw
</blockquote></details>

Done.

---

*[test/getBalanceUnitTest.js, line 61 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5MnRr8pppnnQ3F4a-:-Ka8Zt4qWQ0TvDmTVIMS:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L61)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

let's assert that balance is negative?
</blockquote></details>

Done.

---

*[test/getBalanceUnitTest.js, line 64 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5NJkU-gPk7JiFQSfc:-Ka8cAE-EhFUa5febFfK:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L64)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

The test is functionally correct, but it took me some time to understand. 

Perhaps it would be easier to understand the test if we define
```
let EXTRA_CONTRIBUTION = <something>;
```

then:
```
let debt = -balance;

 yield rosca.contribute({from: accounts[1], value: (debt  + EXTRA_CONTRIBUTION)});
```
and check the withdrawal to be EXTRA_CONTRIBUTION?
</blockquote></details>

Done.

---

*[test/getBalanceUnitTest.js, line 72 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5NnxjMtPMKsuOCiuk:-Ka8ZELk03Gc9tM-YppN:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L72)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

space before ( in ""
</blockquote></details>

Done.

---

*[test/getBalanceUnitTest.js, line 80 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5O1y3LU5LCAnFufm1:-Ka8b5nNDXlAv3Q6gIE0:b-e3dg5a) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L80)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

do you think it's possible to make the ROSCA with less participants, thus making the test smaller and easier to follow?
</blockquote></details>

made it into 3

---

*[test/getBalanceUnitTest.js, line 99 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5OA8potqDvNnQbYoG:-Ka8_HuqlMRJMH6PNzY6:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L99)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

i suggest adding a comment that at this point we expect one of the delinquents to win.
</blockquote></details>

Done.

---

*[test/getBalanceUnitTest.js, line 103 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5ONNXh2vlqMZAJ7og:-Ka8ZOp4qdgkHcDPXudI:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L103)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

s/haven't/has
</blockquote></details>

Done.

---

*[test/getBalanceUnitTest.js, line 104 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5OMtoOA-U2m0aVlvJ:-Ka8ZLhSb45XjVtbJXH4:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L104)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

s/withdrawing/withdraw
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91)*

**Comment by rmerom** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/cleanUpPreviousRoundUnitTest.js, line 108 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5LU0NXmoikcvKJZJi:-Ka8jQSfeeW4wZVqjSk6:bdvpvfg) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/cleanUpPreviousRoundUnitTest.js#L108)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

if we merge it, test will become a significantly long, I am sure you would agree that long test is a lot harder to catch bug and maintain.
</blockquote></details>

That's a good point, and after all it's of course your decision.  The issue I'm raising is that if test 1 does scenario A, and test B does scenario A and then scenario B, it might be worthwhile to merge them, lengthening test 2 by a few more checks of A.

---

*[test/getBalanceUnitTest.js, line 8 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5Odc8UZBa_e-2DL0B:-Ka8jhyrSTZlwW2_mat8:b-6f2uhu) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L8)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

Correct me if I am wrong, you said it would be better to test behaviorally. 
I thought calling withdraw proves that getBalance returns the correct pending withdrawal.
That's why i decide to use withdraw instead of checking the return value with expected value. 
</blockquote></details>

+1 to testing behaviorally.
When we tested withdraw(), we checked that the withdrawn value aligns with our expectations of how much should be withdrawn.
In a similar manner, since getBalance() is a public API too, we can certainly test it against expectations. Again, there's nothing wrong with testing it against withdraw() (as long as the latter is tested against expectations), but it just makes the tests harder to understand.

---

*[test/getBalanceUnitTest.js, line 64 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5NJkU-gPk7JiFQSfc:-Ka8nBUy8PwBi_UwIxoZ:bho7uln) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L64)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thanks, and nit: to make it even easier to follow consider
let EXTRA_CONTRIBUTION = 2e16;   // for example
as there is no real connection to CONTRIBUTION_SIZE and so there's less chance of getting confused with CONTRIBUTION_SIZE

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91)*

**Review by rmerom — APPROVED** [review]

**Comment by shine2lay** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/cleanUpPreviousRoundUnitTest.js, line 108 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5LU0NXmoikcvKJZJi:-Ka8qJPXF76nea9Q902N:b-nstfnq) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/cleanUpPreviousRoundUnitTest.js#L108)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

That's a good point, and after all it's of course your decision.  The issue I'm raising is that if test 1 does scenario A, and test B does scenario A and then scenario B, it might be worthwhile to merge them, lengthening test 2 by a few more checks of A.
</blockquote></details>

there are a number of tests we've written that are very similar to this particular test, where the test B includes test A as well. 
I'll just leave them separated.

---

*[test/getBalanceUnitTest.js, line 8 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5Odc8UZBa_e-2DL0B:-Ka8qrRlX-sSxOxuvlBs:b4q9oui) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L8)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

+1 to testing behaviorally.
When we tested withdraw(), we checked that the withdrawn value aligns with our expectations of how much should be withdrawn.
In a similar manner, since getBalance() is a public API too, we can certainly test it against expectations. Again, there's nothing wrong with testing it against withdraw() (as long as the latter is tested against expectations), but it just makes the tests harder to understand.
</blockquote></details>

ok, i initially wrote the test case against expectations but thought behavioural testing would be better.
I'll add that in before merging

---

*[test/getBalanceUnitTest.js, line 64 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91#-Ka5NJkU-gPk7JiFQSfc:-Ka8qppdaC9ew-P_30Nj:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/7eade087aa594ebffa7230da7f7154e34a5769d8/test/getBalanceUnitTest.js#L64)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

thanks, and nit: to make it even easier to follow consider
let EXTRA_CONTRIBUTION = 2e16;   // for example
as there is no real connection to CONTRIBUTION_SIZE and so there's less chance of getting confused with CONTRIBUTION_SIZE
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/91)*

**Pull request merged**
