### PR TITLE
Change roundTime to be in secs instead of days

### PR DESCRIPTION
**Pull request by rmerom**
Please review carefully as this is not backwards-compatible and I might have broken something w/o noticing.

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/149)

### CODE REVIEW

**Comment by shine2lay** [comment]
Reviewed 16 of 16 files at r1.
Review status: 15 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 86 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149#-KfgxvqpgF29mZOEsXgs:-KfgxvqpgF29mZOEsXgt:b2zri98) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/1365f7abf5d512383c31a367ebdb50591128411e/test/4MemberFullRoscaTest.js#L86)):*
> ```JavaScript
>   const MIN_START_DELAY = 86400 + 10;
>   const ROUND_PERIOD_IN_SECS = 300;
>   const ROUND_PERIOD = ROUND_PERIOD_IN_SECS * 86400;
> ```

I don' t think you would need this line anymore, since round period is now already in seconds

---

*[test/feesUnitTest.js, line 31 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149#-Kfh8a4TlB9OH1O9FI6B:-Kfh8a4TlB9OH1O9FI6C:b-gml0ah) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/1365f7abf5d512383c31a367ebdb50591128411e/test/feesUnitTest.js#L31)):*
> ```JavaScript
>   const START_TIME_DELAY = 86400 + 10;
>   const ROUND_PERIOD_IN_SECS = 30;
>   const ROUND_PERIOD = ROUND_PERIOD_IN_SECS * 86400;
> ```

i don't think you need this line

---

*[tools/perf/gas_usage.js, line 47 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149#-Kfh9pEbcrYBkULj8ibl:-Kfh9pEbcrYBkULj8ibm:bfx9rg8) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/1365f7abf5d512383c31a367ebdb50591128411e/tools/perf/gas_usage.js#L47)):*
> ```JavaScript
>     
>     yield utils.getGasUsage(rosca.bid(CONTRIBUTION_SIZE * (memberList.length + 1), {from: accounts[round - 1]}), "bid");
>     utils.increaseTime(ROUND_PERIOD_IN_SECS * 86400);
> ```

you don't need to multiply by 86400

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149)*

**Review by shine2lay — APPROVED** [review]

**Comment by morelazers** [comment]
Review status: 15 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[contracts/ROSCA.sol, line 186 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149#-KfhEOpnHxTdA_zffw1V:-KfhEOpnHxTdA_zffw1W:b-2z15te) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/aa8ae916d759860f968a5219c09552da4fbafd6c/contracts/ROSCA.sol#L186)):*
> ```
>       address[] members_,
>       uint16 serviceFeeInThousandths_) {
>     if (roundPeriodInSecs_ == 0) {
> ```

What about negative values? (I guess they're impossible with unsigned int though right?) Also I'm not 100% why we need this constraint, could you elaborate on the reasoning?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149)*

**Comment by rmerom** [comment]
Thanks guys. Not next to my laptop right now so will fix this later. Shine,
you're right, I'll fix the leftovers.
Tom, having a round time of 0 is not an actual use case and may cause us a
division-by-zero at some point in future.

**Review by morelazers — APPROVED** [review]

**Comment by rmerom** [comment]
Review status: 15 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/4MemberFullRoscaTest.js, line 86 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149#-KfgxvqpgF29mZOEsXgs:-KfiZ4RADBFRwjKjaJPY:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/1365f7abf5d512383c31a367ebdb50591128411e/test/4MemberFullRoscaTest.js#L86)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

I don' t think you would need this line anymore, since round period is now already in seconds
</blockquote></details>

Done.

---

*[test/feesUnitTest.js, line 31 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149#-Kfh8a4TlB9OH1O9FI6B:-KfiZDB3LmmKkmUjjuDz:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/1365f7abf5d512383c31a367ebdb50591128411e/test/feesUnitTest.js#L31)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

i don't think you need this line
</blockquote></details>

Done.

---

*[tools/perf/gas_usage.js, line 47 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149#-Kfh9pEbcrYBkULj8ibl:-KfiZYPklMnCuir-AcQN:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/1365f7abf5d512383c31a367ebdb50591128411e/tools/perf/gas_usage.js#L47)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

you don't need to multiply by 86400
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/149)*

**Pull request merged**
