### PR TITLE
Split Credit into Contributions & winnings

### PR DESCRIPTION
**Pull request by shine2lay**
I can still think of some test cases that i haven't written yet i'll work more on it later.

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/54)

### CODE REVIEW

**Comment by rmerom** [comment]
I'll be happy to review a bit later. Re the tests that you want to add, would you be ok for the time being just adding their names so that i can see what you're planning? e.g. 
```
it("checks if something", co(function* () {
  // TODO(shine): implement
}
```

**Comment by rmerom** [comment]
Just reviewed some of ROSCA.sol . Let's get these comments addressed and continue.
Note however, if some of the comments do point to a bug, could you make sure we have a test that covers that bug? (you can implement it later, but just put it in place, similar to what the previous comment meant)

---

Review status: 0 of 8 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 189 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_82ssEcYPnfoDjvjwC:-K_82ssEcYPnfoDjvjwD:b-nz8ric) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L189)):*
> ```
>     if (winnerAddress == 0) {
>       // There is no bid in this round. Find an unpaid address for this epoch.
>       address lastUnPaid = 0x0;
> ```

s/lastUnpaid

---

*[contracts/ROSCA.sol, line 194 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_82n9DGfxN2wYsSwsk:-K_82n9ESQW8LZCyEEak:b-a2tfjl) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L194)):*
> ```
>         address candidate = membersAddresses[(semi_random + i) % membersAddresses.length];
>         if (!members[candidate].paid) {
>           if(members[candidate].contributions + (totalDiscounts / membersAddresses.length) >= (currentRound * contributionSize)) { // check if the member is in good standing
> ```

s/if(if (

---

*[contracts/ROSCA.sol, line 212 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_831vicTJPQu33hJcS:-K_831vicTJPQu33hJcT:beyigdg) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L212)):*
> ```
>     LogRoundFundsReleased(winnerAddress, lowestBid);
> 
>     // use winnings to satisfy the contribution requirement if member forgot to contribute this round
> ```

I'm not sure "forgot" is the right term here. Once they win, they are completely entitled to use any unwithdrawn money to pay for their contributions.

---

*[contracts/ROSCA.sol, line 215 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_83D6W4R6bhEcj7jCV:-K_83D6W4R6bhEcj7jCW:byc7zfn) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L215)):*
> ```
>     for (uint16 j = 0; j < membersAddresses.length; j++) {
>       User member = members[membersAddresses[j]];
>       uint256 discount = totalDiscounts / membersAddresses.length;
> ```

please move this to before the loop to save on gas

---

*[contracts/ROSCA.sol, line 216 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_83FveehesMCkmHPxU:-K_83FveehesMCkmHPxV:b-qvn5oe) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L216)):*
> ```
>       User member = members[membersAddresses[j]];
>       uint256 discount = totalDiscounts / membersAddresses.length;
>       if(member.winnings != 0 && member.contributions < contributionSize * currentRound + 1 &&
> ```

s/if(/if (

also below

---

*[contracts/ROSCA.sol, line 216 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_8405uieBNDW5JXhui:-K_8405uieBNDW5JXhuj:b-c8f2bl) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L216)):*
> ```
>       User member = members[membersAddresses[j]];
>       uint256 discount = totalDiscounts / membersAddresses.length;
>       if(member.winnings != 0 && member.contributions < contributionSize * currentRound + 1 &&
> ```

shouldn't this be 
```
... .contributions < contributionSize * (currentRound + 1)
```
?

---

*[contracts/ROSCA.sol, line 216 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_85pieLokfkXxbgUeo:-K_85pieLokfkXxbgUep:bb2e4rx) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L216)):*
> ```
>       User member = members[membersAddresses[j]];
>       uint256 discount = totalDiscounts / membersAddresses.length;
>       if(member.winnings != 0 && member.contributions < contributionSize * currentRound + 1 &&
> ```

is there a reason we not including ```discounts``` here, but we are including it in the next line?

---

*[contracts/ROSCA.sol, line 217 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_84HYMJsqiSUhw9xuK:-K_84HYMJsqiSUhw9xuL:b2pumum) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L217)):*
> ```
>       uint256 discount = totalDiscounts / membersAddresses.length;
>       if(member.winnings != 0 && member.contributions < contributionSize * currentRound + 1 &&
>         member.contributions + discount >= contributionSize * currentRound) {
> ```

please indent by 4

---

*[contracts/ROSCA.sol, line 282 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_86ClPU3DT6ssRmLeN:-K_86ClPU3DT6ssRmLeO:b-m1pcyk) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L282)):*
> ```
>    */
>   function withdraw() onlyFromMember onlyIfEscapeHatchInactive external returns(bool success) {
>     uint256 memberContributions = members[msg.sender].contributions + totalDiscounts / membersAddresses.length;
> ```

for readability, you might want to do something similar to what you did in cleanUpPreviousRound():
```User sender = members[msg.sender];```
```


---

*[contracts/ROSCA.sol, line 285 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_86m8w3HscsfxSo1fW:-K_86m8w3HscsfxSo1fX:b-fa2v6c) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L285)):*
> ```
>     uint256 totalCredit = memberContributions + members[msg.sender].winnings;
>     uint256 totalDebit = currentRound * contributionSize;
>     if (totalDebit > memberContributions || totalDebit >= totalCredit) throw;  // needs to be in good Standing in order to withdraw funds
> ```

This and the next lines are quite complicated accounting, and I'm sure you put a lot of thought about how to do it this specific way. 
Could you add comments explaining *why* things are calculated the way they are, and later on also what each if means?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-:-K_87ZTi2Jg1zn6-P5h7:b2eknre)*
<!-- Sent from Reviewable.io -->

**Comment by shine2lay** [comment]
Review status: 0 of 8 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 189 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_82ssEcYPnfoDjvjwC:-K_AIKvxmlBa1ETBXOwT:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L189)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

s/lastUnpaid
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 194 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_82n9DGfxN2wYsSwsk:-K_AIRlPPU--afIdfbTJ:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L194)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

s/if(if (
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 212 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_831vicTJPQu33hJcS:-K_AIswDhn7GgWQoY71Z:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L212)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

I'm not sure "forgot" is the right term here. Once they win, they are completely entitled to use any unwithdrawn money to pay for their contributions.
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 215 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_83D6W4R6bhEcj7jCV:-K_AJlkoeFGyWrG_yRbq:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L215)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

please move this to before the loop to save on gas
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 216 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_83FveehesMCkmHPxU:-K_AJqr98ksfYPC2KHy4:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L216)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

s/if(/if (

also below
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 216 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_8405uieBNDW5JXhui:-K_AJrZSOUhOA2uddSXl:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L216)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

shouldn't this be 
```
... .contributions < contributionSize * (currentRound + 1)
```
?
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 216 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_85pieLokfkXxbgUeo:-K_AJsVbDHdauB-xSqvi:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L216)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

is there a reason we not including ```discounts``` here, but we are including it in the next line?
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 217 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_84HYMJsqiSUhw9xuK:-K_AJvhiICbsAiXgggP0:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L217)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

please indent by 4
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 282 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_86ClPU3DT6ssRmLeN:-K_AUoqrSoolwovFCr_p:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L282)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

for readability, you might want to do something similar to what you did in cleanUpPreviousRound():
```User sender = members[msg.sender];```

</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 285 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_86m8w3HscsfxSo1fW:-K_AUmudombEHzPKF06Z:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/contracts/ROSCA.sol#L285)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

This and the next lines are quite complicated accounting, and I'm sure you put a lot of thought about how to do it this specific way. 
Could you add comments explaining *why* things are calculated the way they are, and later on also what each if means?
</blockquote></details>

Done.

---

*[test/withdrawUnitTest.js, line 113 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_7WPsinxGCNxtzzbtL-r1-113:-K_AK7nKPBjCmR2ZocHD:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/test/withdrawUnitTest.js#L113)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

'totalFees' is defined but never used.
</blockquote></details>

Done.

---

*[test/withdrawUnitTest.js, line 150 at r1](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_7WPsinxGCNxtzzbtL-r1-150:-K_AKHqSedLWzrGZZvAf:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/20439f98ffaff1bf7809b680cb028c4a6711ea94/test/withdrawUnitTest.js#L150)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

Line is too long.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54)*

**Comment by rmerom** [comment]
Review status: 0 of 8 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[testrpc_command.sh, line 11 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_AnnJh2HB9FuODmcKW:-K_AnnJh2HB9FuODmcKX:brug39t) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/testrpc_command.sh#L11)):*
> ```Shell
>         --account="0xa453611d9419d0e56f499079478fd72c37b251a94bfde4d19872c44cf65386e3, 10000000000000000000000000"\
>         --account="0x829e924fdf021ba3dbbc4225edfece9aca04b929d6e75613329ca6f1d31c0bb4, 10000000000000000000000000"\
>         --account="0xb0057716d5917badaf911b193b12b910811c1497b5bada8d7711f758981c3773, 10000000000000000000000000"
> ```

nit: let's make sure to merge this with the existing testrpc_command.sh (we added the account addresses below)

---

*[contracts/ROSCA.sol, line 212 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_AoV2cM5mKTFBJeS3q:-K_AoV2cM5mKTFBJeS3r:bti2vf6) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L212)):*
> ```
>     LogRoundFundsReleased(winnerAddress, lowestBid);
> 
>     // use winnings to satisfy the contribution requirement if member didn't contribute this round
> ```

maybe add: "however, if user is delinquent (i.e. hasn't paid in previous rounds either), they cannot use their winning to cover for the contributions.

---

*[contracts/ROSCA.sol, line 286 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_Aqz1j1wAMSpnHEN2N:-K_Aqz1j1wAMSpnHEN2O:b-qtfwb2) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L286)):*
> ```
>     uint256 totalCredit = memberContributions + sender.winnings;
>     uint256 totalDebit = currentRound * contributionSize;
>     // first check if member is good standing, then check if there is anything to withdraw, if not throw
> ```

Thanks. While I was reading the comment, I thought it was referring to the entire next section (because of "first", "then"), and the throw is probably pretty self-evident.
Consider:
// Verify member is in good standing and there are any funds to withdraw.

---

*[contracts/ROSCA.sol, line 289 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_ApUaVFEHx0_PHbcv3:-K_ApUaVFEHx0_PHbcv4:b-8m5n1r) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L289)):*
> ```
>     if (totalDebit > memberContributions || totalDebit >= totalCredit) throw;
> 
>     uint256 amountToWithdraw = memberContributions - totalDebit ;
> ```

/ ;/;

---

*[contracts/ROSCA.sol, line 289 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_ApZIwzX9HZNsa-tjf:-K_ApZIwzX9HZNsa-tjg:b-3pi1ek) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L289)):*
> ```
>     if (totalDebit > memberContributions || totalDebit >= totalCredit) throw;
> 
>     uint256 amountToWithdraw = memberContributions - totalDebit ;
> ```

shouldn't this be named "contributionsToWithdraw"? "amountToWithdraw" sounds to me like it is the total amount.
same for amountAfterFee.

---

*[contracts/ROSCA.sol, line 294 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_ArVb56SAknY7qeaGc:-K_ArVb56SAknY7qeaGd:bjwk50g) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L294)):*
> ```
>     uint256 winningsAfterFee = winningsToWithdraw / 1000 * (1000 - serviceFeeInThousandths);
> 
>     uint256 contractBalance = this.balance - totalFees;
> ```

consider s/contractBalance/contractNetBalance
(I missed the var declaration and when I read it being used I  assumed it's simply ```this.balance```)

---

*[contracts/ROSCA.sol, line 298 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_AqmnJFY1AlfcVh-9U:-K_AqmnKPNDrsD8-i2Ut:b-nefkcp) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L298)):*
> ```
>     // check if contract's balance is less than total amount to withdraw
>     if (contractBalance < amountAfterFee + winningsAfterFee) {
>       LogCannotWithdrawFully(amountAfterFee + winningsAfterFee,  this.balance - totalFees); // Let user withdraw the funds into a safe place
> ```

not sure I understand the value of the comment

---

*[contracts/ROSCA.sol, line 300 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_Ar3Mi0IfDug7vy_mv:-K_Ar3Mi0IfDug7vy_mw:b-hwlqvk) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L300)):*
> ```
>       LogCannotWithdrawFully(amountAfterFee + winningsAfterFee,  this.balance - totalFees); // Let user withdraw the funds into a safe place
> 
>       if (contractBalance > amountAfterFee) {  // balance is greater than amountAfterFee but less than winnings account
> ```

Great that you added a comment. The comment though explains *what* this code is doing, which is pretty understandable from the code itself. I think it would be more useful to have a comment explain *why* the code is doing this so that a reader can understand a) if the algorithm makes sense and b) whether the code satisfies the algorithm.

---

*[contracts/ROSCA.sol, line 302 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_ArkVCOUa4NFcqrt2I:-K_ArkVCOUa4NFcqrt2J:b-kw580d) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L302)):*
> ```
>       if (contractBalance > amountAfterFee) {  // balance is greater than amountAfterFee but less than winnings account
>         contractBalance -= amountAfterFee;
>         winningsAfterFee = contractBalance;
> ```

I'm sorry, I don't understand this. I might be able to guess why we're doing this, but a good comment can go a long way explaining what this is all about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54)*

**Comment by shine2lay** [comment]
Review status: 0 of 8 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[testrpc_command.sh, line 11 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_AnnJh2HB9FuODmcKW:-K_BoPPGA0VHrJx9QBuH:bt31huo) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/testrpc_command.sh#L11)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

nit: let's make sure to merge this with the existing testrpc_command.sh (we added the account addresses below)
</blockquote></details>

i'll delete it before merging so it shouldn't have a problem 

---

*[contracts/ROSCA.sol, line 212 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_AoV2cM5mKTFBJeS3q:-K_BjLNOb8jLUBrltqGt:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L212)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

maybe add: "however, if user is delinquent (i.e. hasn't paid in previous rounds either), they cannot use their winning to cover for the contributions.
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 286 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_Aqz1j1wAMSpnHEN2N:-K_BjTbILnDbMm40P2rs:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L286)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

Thanks. While I was reading the comment, I thought it was referring to the entire next section (because of "first", "then"), and the throw is probably pretty self-evident.
Consider:
// Verify member is in good standing and there are any funds to withdraw.
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 289 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_ApUaVFEHx0_PHbcv3:-K_BjZ6AMpe_Xk-ma4rT:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L289)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

/ ;/;
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 289 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_ApZIwzX9HZNsa-tjf:-K_BmaIhROLK-6Qf20xi:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L289)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

shouldn't this be named "contributionsToWithdraw"? "amountToWithdraw" sounds to me like it is the total amount.
same for amountAfterFee.
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 294 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_ArVb56SAknY7qeaGc:-K_BmZo6FJ8LwyTbdJ6Y:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L294)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

consider s/contractBalance/contractNetBalance
(I missed the var declaration and when I read it being used I  assumed it's simply ```this.balance```)
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 298 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_AqmnJFY1AlfcVh-9U:-K_BhwlBE91ATjJHJuFR:blbkh3v) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L298)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

not sure I understand the value of the comment
</blockquote></details>

that's the comment you wrote,i didn't delete any existing comments while i was doing the changes

---

*[contracts/ROSCA.sol, line 300 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_Ar3Mi0IfDug7vy_mv:-K_BrrpzgM4kBtIXmhPJ:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L300)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

Great that you added a comment. The comment though explains *what* this code is doing, which is pretty understandable from the code itself. I think it would be more useful to have a comment explain *why* the code is doing this so that a reader can understand a) if the algorithm makes sense and b) whether the code satisfies the algorithm.
</blockquote></details>

Done.

---

*[contracts/ROSCA.sol, line 302 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_ArkVCOUa4NFcqrt2I:-K_BrsAwTopnOgFao0e4:b-896fix) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L302)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

I'm sorry, I don't understand this. I might be able to guess why we're doing this, but a good comment can go a long way explaining what this is all about.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54)*

**Comment by rmerom** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 298 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_AqmnJFY1AlfcVh-9U:-K_C7kykFjQMGdTXhr5B:b-1zv9q7) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L298)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

that's the comment you wrote,i didn't delete any existing comments while i was doing the changes
</blockquote></details>

my comments don't have any special importance, feel free to delete them when they're no longer valuable :)

---

*[contracts/ROSCA.sol, line 302 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_ArkVCOUa4NFcqrt2I:-K_CA9hyQ5h4hy0zAFz1:b-123w1h) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/5852683bea5bc13ed9cde804f016ac5eab5dacc2/contracts/ROSCA.sol#L302)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I still don't understand... could you add a general comment giving an overview how these calculations add up? I'll also be happy to speak on phone/slack

---

*[contracts/ROSCA.sol, line 240 at r4](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_CAWYJqDMabDrM9xIM:-K_CAWYKJv7K95mwPzBk:bwz2fcx) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/cf3ae16922618905f7656e14e8bc780b04803e51/contracts/ROSCA.sol#L240)):*
> ```
>     // TODO(ron): this has a bad edge case: it will take fees of any excessive contributions made.
>     // Fix this once we switch to the contributions/winnings model.
>     totalFees += msg.value / 1000 * serviceFeeInThousandths;
> ```

wasn't one of the reasons  we're making the change is so that we calculate fees more correctly? (and not taking fees on overcontribrutions)

---

*[contracts/ROSCA.sol, line 303 at r4](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_C9vsuQXxaLBttYgfm:-K_C9vsuQXxaLBttYgfn:b-585fes) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/cf3ae16922618905f7656e14e8bc780b04803e51/contracts/ROSCA.sol#L303)):*
> ```
>       // contractBalance can be more than one account or less than both
>       if (contractNetBalance > contributionAfterFee) {
>         contractNetBalance -= contributionAfterFee;
> ```

I don't understand why here and in other places we change contractNetBalance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54)*

**Comment by rmerom** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 302 at r4](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54#-K_C_-T78V5zuJZVGiTG:-K_C_-T78V5zuJZVGiTH:bqh3msz) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/cf3ae16922618905f7656e14e8bc780b04803e51/contracts/ROSCA.sol#L302)):*
> ```
> 
>       // contractBalance can be more than one account or less than both
>       if (contractNetBalance > contributionAfterFee) {
> ```

Ignoring the fees from now (which we're anyway discussing on slack), what do you think of the readability of the following compared to the if/else chain?
```
  function min(uint256 a, uint256 b) {
      if (a <= b) {
          return a;
      }
      return b;
  }
```

and then in withdraw():
```
    uint256 extraContributions = sender.totalContributions + totalDiscounts / members.length - totalDebit;

    uint256 fromContributions = min(extraContributions, contractBalance);
    uint256 fromWinnings = min(contractBalance - fromContributions, sender.winnings);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/54)*

**Pull request closed without merging**
