### PR TITLE
Underflow bug fix + Contract cleanup + set smaller max fee

### PR DESCRIPTION
**Pull request by rmerom**
* Cleans up some of the documentation and code.
* Sets the maximum fee to 2% instead of 20%

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/rosca-contracts/9)

### CODE REVIEW

**Comment by shine2lay** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[contracts/ROSCA.sol, line 119 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXg81chxGZKKSaI9u_D:-KXg81ciGTUX7bUkRmWv:bvu2vn6) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L119)):*
> ```
>       // We reset to one more than the pot, so that participants can bid the actual
>       // pot size.
>       lowestBid = contributionSize * membersAddresses.length + 1;
> ```

should we still make it pot+1? I think it'll be a better choice to keep it at pot, because someone can just bid pot and win it 100%. I think users should bid only if they want to receive less than the pot

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by shine2lay** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[contracts/ROSCA.sol, line 197 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXg9HMzw1FKjcfvguZS:-KXg9HMzw1FKjcfvguZT:boyiky1) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L197)):*
> ```
>     uint totalDebit = currentRound * contributionSize;
>     if (totalDebit >= totalCredit) {  // nothing to withdraw
>         return false;
> ```

one thing i realized is return values is only valuable with "call" function, not "transaction" if you use do a transaction call, it'll only return tx_id on success or throw on failure, there is no real way to identify if it returns a false on it. So i think we should throw instead of return false;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by rmerom** [comment]
Thanks for reviewing!

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[contracts/ROSCA.sol, line 119 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXg81chxGZKKSaI9u_D:-KXgRKz1i-5ofPnDT3tN:b-yuio84) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L119)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

should we still make it pot+1? I think it'll be a better choice to keep it at pot, because someone can just bid pot and win it 100%. I think users should bid only if they want to receive less than the pot
</blockquote></details>

Well, if we keep it at pot, participants will be still able to bit at (pot - 1 wei). I think it'll just be less user friendly (because they won't understand what's going on). What do you think?

---

*[contracts/ROSCA.sol, line 197 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXg9HMzw1FKjcfvguZS:-KXgRYe71wbTq7Wen6ZV:bx1yqjt) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L197)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

one thing i realized is return values is only valuable with "call" function, not "transaction" if you use do a transaction call, it'll only return tx_id on success or throw on failure, there is no real way to identify if it returns a false on it. So i think we should throw instead of return false;
</blockquote></details>

Yes, that's true. The return value is only meaningful if users use contracts to manage their ROSCA participation. Do you prefer we remove the function return value? I don't mind either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-:-KXgRl89R6WHkLlhCNJ0:b-yz40g0)*

**Comment by rmerom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[contracts/ROSCA.sol, line 197 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXg9HMzw1FKjcfvguZS:-KXgSmuuU3YV-nStGqmy:bfnt4jn) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L197)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

Yes, that's true. The return value is only meaningful if users use contracts to manage their ROSCA participation. Do you prefer we remove the function return value? I don't mind either way.
</blockquote></details>

Actually, I think whether the function returns a boolean is orthogonal to throwing or not. Even if there's no return value, we can just return when a user has nothing to withdraw. Users will have to look for LogFundsWithdrawal to know if their funds were withdrawn.
I hope next week we'll be able to hear more from Ben about the return vs. throw issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by shine2lay** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[contracts/ROSCA.sol, line 119 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXg81chxGZKKSaI9u_D:-KXg_fHbnj9Ov1nXG_64:b-um1fq0) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L119)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

Well, if we keep it at pot, participants will be still able to bit at (pot - 1 wei). I think it'll just be less user friendly (because they won't understand what's going on). What do you think?
</blockquote></details>

this is my thought process, if we have it at pot+1 , the first person to bid will get the pot without any TD(total discount), i think everyone should have equal chance of winning the pot if the the size of the Pot is at default. I don't mind keeping it the way it is, its just a thought that came to mind and i thought i should get your opinion.

---

*[contracts/ROSCA.sol, line 197 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXg9HMzw1FKjcfvguZS:-KXgaSsaq4P-semDtvA1:bkx2vvc) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L197)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

Actually, I think whether the function returns a boolean is orthogonal to throwing or not. Even if there's no return value, we can just return when a user has nothing to withdraw. Users will have to look for LogFundsWithdrawal to know if their funds were withdrawn.
I hope next week we'll be able to hear more from Ben about the return vs. throw issue.
</blockquote></details>

i think i mentioned this before, mist wallet kind of "test call" the function for you to see if it will throw given the parameters, and give you a warning if it does, this can help user prevent a loss of transaction gas. I was hoping we can implement similar one in the frontend.  return value would not be as efficient

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by rmerom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[contracts/ROSCA.sol, line 119 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXg81chxGZKKSaI9u_D:-KXgeGoySAo0Dk-c43Y6:bjqmg3y) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L119)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

this is my thought process, if we have it at pot+1 , the first person to bid will get the pot without any TD(total discount), i think everyone should have equal chance of winning the pot if the the size of the Pot is at default. I don't mind keeping it the way it is, its just a thought that came to mind and i thought i should get your opinion.
</blockquote></details>

I understand your concern that someone can just bid to get the pot at a certain round. I'm personally not sure there's anything wrong with it (if no one care,s and one person wants the pot, why not have it?).
However, as I mentioned, setting the initial value to pot doesn't help much for this case, because the bidder will simply bid (pot - 1wei) which is about pot - $1e-17. It won't have any monetary value whatsoever as long as there are no other bidders....

---

*[contracts/ROSCA.sol, line 197 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXg9HMzw1FKjcfvguZS:-KXgewvaXaGbUXSM0m_R:b9lsys8) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L197)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

i think i mentioned this before, mist wallet kind of "test call" the function for you to see if it will throw given the parameters, and give you a warning if it does, this can help user prevent a loss of transaction gas. I was hoping we can implement similar one in the frontend.  return value would not be as efficient
</blockquote></details>

OK, done :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by shine2lay** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 171 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXl97dz99LyPLiTSiXo:-KXl97dz99LyPLiTSiXp:b-pp2oxr) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L171)):*
> ```
>     if (members[msg.sender].paid  ||
>         currentRound == 0 ||
>         members[msg.sender].credit - (currentRound * contributionSize) - (totalDiscounts / membersAddresses.length) < 0 ||
> ```

i found this out during testing, we have to cast it as int() after calculation, and also + (totalDiscounts/ membersAddress.length)

---

*[contracts/ROSCA.sol, line 176 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXl9ePfVGVuMmCj4SQt:-KXl9ePfVGVuMmCj4SQu:b-rmsugd) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L176)):*
> ```
>     if (bidInWei >= lowestBid) {
>       // Bid cannot win. We don't throw as this may be hard for frontend
>       // to predict on the one hand, and would waste the caller's gas on
> ```

why is it hard for frontEnd to predict? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by rmerom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 171 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXl97dz99LyPLiTSiXo:-KXlA_QyxvT3o8Z-kZfu:b-vl1jgo) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L171)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

i found this out during testing, we have to cast it as int() after calculation, and also + (totalDiscounts/ membersAddress.length)
</blockquote></details>

that's right! I might actually change that to something maybe more readable that doesn't require a cast:
members[msg.sender].credit + (totalDiscounts / membersAddresses.length) < (currentRound * conributionSize)

---

*[contracts/ROSCA.sol, line 176 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXl9ePfVGVuMmCj4SQt:-KXlApP888G94XO7TXeU:b-asfusc) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L176)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

why is it hard for frontEnd to predict? 
</blockquote></details>

I thought so because other participants may bid at roughly the same time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by shine2lay** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[contracts/ROSCA.sol, line 176 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXl9ePfVGVuMmCj4SQt:-KXlBL2fYDViWLnPJ7-k:bja3ks0) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L176)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

I thought so because other participants may bid at roughly the same time
</blockquote></details>

Ok, either way works, but with this, you'll have to take care of notifying the user of the fail bid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by shine2lay** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[contracts/ROSCA.sol, line 141 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXlBiSpg4XEnSCRttdW:-KXlBiSpg4XEnSCRttdX:b-9ftjao) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L141)):*
> ```
>       lowestBid--;
>     }
>     totalDiscounts += contributionSize - lowestBid;
> ```

(contributionSize * membersAddresses.length) - lowestBid
or it'll always be negative

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by shine2lay** [comment]
There will be conflict with merging, i am not sure how to deal with it, do you?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-:-KXlBsZvGzxfgREraf69:b-ncfpbr)*

**Comment by rmerom** [comment]
yes, i'm googling it and i think it'll be ok. Good to learn all this stuff using git... :)

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[contracts/ROSCA.sol, line 141 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXlBiSpg4XEnSCRttdW:-KXlCz38VRWliruvKG0L:bb6un1j) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L141)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

(contributionSize * membersAddresses.length) - lowestBid
or it'll always be negative
</blockquote></details>

Done

---

*[contracts/ROSCA.sol, line 176 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXl9ePfVGVuMmCj4SQt:-KXlCjez9y0XaPYdE1I3:b-k3yayx) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L176)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

Ok, either way works, but with this, you'll have to take care of notifying the user of the fail bid
</blockquote></details>

anyway the best way to make sure a bid was registered is to listen for the event...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-:-KXlCtMLxhDdZIRHJHc3:brkuoj1)*

**Comment by shine2lay** [comment]
ok,i'll approve the file and PR so you can merge it

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[contracts/ROSCA.sol, line 176 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXl9ePfVGVuMmCj4SQt:-KXlLWSTLqr_az_XZ0Sa:bj7iadu) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L176)):*
<details><summary><i>Previously, rmerom (Ron Merom) wrote…</i></summary><blockquote>

anyway the best way to make sure a bid was registered is to listen for the event...
</blockquote></details>

server is always going to be watching for all events I am sure , just to keep a log

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-:-KXlLf73nCCVDoeUtnDv:b-o75vkk)*

**Comment by shine2lay** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Review by shine2lay — APPROVED** [review]

**Comment by shine2lay** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Comment by shine2lay** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-:-KXlMGW99ST0SorqJgTM:bnfp4nl)*

**Comment by rmerom** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[contracts/ROSCA.sol, line 176 at r2](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9#-KXl9ePfVGVuMmCj4SQt:-KXlX7_7JDTJqkjy3Sz4:b6jo905) ([raw file](https://github.com/wetrustplatform/rosca-contracts/blob/6dc830e400e951faf2a502d1ea1e2cc826c85e62/contracts/ROSCA.sol#L176)):*
<details><summary><i>Previously, shine2lay wrote…</i></summary><blockquote>

server is always going to be watching for all events I am sure , just to keep a log
</blockquote></details>

yes, this is the proper way to know that a bid was registered (and maybe waiting another X blocks after receiving the event, to see no fork happened)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wetrustplatform/rosca-contracts/9)*

**Pull request merged**
